# Step 3: Calculate Evaluation Metrics - Template

This notebook template calculates comprehensive metrics from the LLM evaluations for any variant.
**Instructions**: Update the VARIANT variable below to specify which variant to analyze.

## L1 Metrics (Retrieval-Path Level)
- Violation Rate at K per retrieval path (lexical, kNN, hybrid)
- Precision@K per retrieval path
- UNCLEAR Rate per retrieval path

## L2 Metrics (End-to-End)
- Overall Violation Rate at K
- Overall Precision@K 
- Zero-Result Rate
- UNCLEAR Rate

## Breakdown Analysis
- Violation rates by negative intent type
- Search term patterns and examples
- Endpoint performance comparison

In [1]:
import pandas as pd
import json
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

# Set up plotting
plt.style.use('default')
sns.set_palette("husl")
%matplotlib inline

## Configuration

In [2]:
# Configuration - UPDATE VARIANT HERE
VARIANT = "control"  # Change to: "control", "treatment_v1", "treatment_v2", etc.

SEARCH_RESULTS_DIR = "./search_results"
MERGED_RESULTS_DIR = f"./llm_evaluations/merged_csv_results/{VARIANT}"
LLM_EVALUATIONS_DIR = "./llm_evaluations"
METRICS_OUTPUT_DIR = f"./metrics_output/{VARIANT}"
os.makedirs(METRICS_OUTPUT_DIR, exist_ok=True)

# Evaluation parameters
K_VALUES = [4, 10, 36]  # Different K values for Precision@K and Violation Rate@K
DEFAULT_K = 36  # Primary K value for reporting

print(f"Variant: {VARIANT.upper()}")
print(f"Merged results directory: {MERGED_RESULTS_DIR}")
print(f"LLM evaluations directory: {LLM_EVALUATIONS_DIR}")
print(f"Metrics output directory: {METRICS_OUTPUT_DIR}")
print(f"K values for evaluation: {K_VALUES}")
print(f"Default K: {DEFAULT_K}")

Variant: CONTROL
Merged results directory: ./llm_evaluations/merged_csv_results/control
LLM evaluations directory: ./llm_evaluations
Metrics output directory: ./metrics_output/control
K values for evaluation: [4, 10, 36]
Default K: 36

## Load Data

In [3]:
def load_merged_csv_results():
    """Load merged CSV results with LLM evaluations from step 2b"""
    
    all_results = []
    csv_files = []
    
    # Walk through merged results directory to find CSV files
    for root, dirs, files in os.walk(MERGED_RESULTS_DIR):
        for file in files:
            if file.endswith('.csv'):
                full_path = os.path.join(root, file)
                rel_path = os.path.relpath(full_path, MERGED_RESULTS_DIR)
                csv_files.append((full_path, rel_path))
    
    print(f"Loading {len(csv_files)} merged CSV files...")
    
    for full_path, rel_path in csv_files:
        try:
            df = pd.read_csv(full_path)
            
            # Extract endpoint type from filename
            filename = os.path.basename(rel_path)
            if filename.endswith('_search_results.csv'):
                endpoint_type = filename.replace('_search_results.csv', '')
            else:
                endpoint_type = os.path.splitext(filename)[0]  # fallback to filename without extension
            
            # Add metadata
            df['source_file'] = rel_path
            df['variant'] = VARIANT
            df['endpoint_type'] = endpoint_type
            
            # Filter for rows with LLM evaluations (negative intent queries)
            df_with_eval = df.dropna(subset=['llm_judgment']).copy()
            
            if len(df_with_eval) > 0:
                all_results.append(df_with_eval)
                print(f"  Loaded {len(df_with_eval)} evaluations from {endpoint_type} endpoint")
                    
        except Exception as e:
            print(f"Error loading {rel_path}: {e}")
            continue
    
    if all_results:
        combined_df = pd.concat(all_results, ignore_index=True)
        return combined_df
    else:
        print("Warning: No merged CSV files with LLM evaluations found")
        return pd.DataFrame()

def load_llm_evaluations():
    """Load LLM evaluation results for reference"""
    
    eval_file = os.path.join(LLM_EVALUATIONS_DIR, 'pair_judgments/final_evaluations.json')
    
    if not os.path.exists(eval_file):
        print(f"Warning: Evaluation file not found: {eval_file}")
        return pd.DataFrame()
    
    with open(eval_file, 'r') as f:
        evaluations = json.load(f)
    
    return pd.DataFrame(evaluations)

# Load merged data with evaluations
df_merged_results = load_merged_csv_results()
df_evaluations_ref = load_llm_evaluations()

print(f"\nMerged results with evaluations: {len(df_merged_results)} entries")
if len(df_evaluations_ref) > 0:
    print(f"Reference evaluations: {len(df_evaluations_ref)} entries")

if len(df_merged_results) > 0:
    print(f"\nColumns in merged data: {list(df_merged_results.columns)}")
    print(f"\n=== JUDGMENT DISTRIBUTION ===")
    judgment_counts = df_merged_results['llm_judgment'].value_counts()
    print(judgment_counts)
    print(f"\nPercentages:")
    for judgment, count in judgment_counts.items():
        print(f"  {judgment}: {count/len(df_merged_results)*100:.1f}%")
    
    print(f"\n=== VIOLATION RATE BY NEGATIVE INTENT ===")
    # Calculate violation rate by negative intent (excluding UNCLEAR)
    clear_judgments = df_merged_results[df_merged_results['llm_judgment'].isin(['VIOLATION', 'COMPLIANT'])]
    if len(clear_judgments) > 0:
        violation_by_intent = clear_judgments.groupby('negative_intent')['llm_judgment'].apply(
            lambda x: (x == 'VIOLATION').mean() * 100
        ).sort_values(ascending=False)
        print(violation_by_intent)
else:
    print("No data loaded. Please run step 2b first to generate merged CSV results.")

Loading 4 merged CSV files...
  Loaded 28465 evaluations from l1_hybrid endpoint
  Loaded 28465 evaluations from l2 endpoint
  Loaded 28609 evaluations from knn endpoint
  Loaded 26423 evaluations from lexical endpoint

Merged results with evaluations: 111962 entries
Reference evaluations: 67702 entries

Columns in merged data: ['search_term', 'endpoint_type', 'rank', 'doc_id', 'part_number', 'sku_name', 'score', 'negative_intent', 'llm_judgment', 'source_file', 'variant']

=== JUDGMENT DISTRIBUTION ===
llm_judgment
COMPLIANT    68834
VIOLATION    31181
UNCLEAR      11947
Name: count, dtype: int64

Percentages:
  COMPLIANT: 61.5%
  VIOLATION: 27.8%
  UNCLEAR: 10.7%

=== VIOLATION RATE BY NEGATIVE INTENT ===
negative_intent
kibble        100.000000
yeast         100.000000
grain, fat    100.000000
no bark       100.000000
bell          100.000000
                 ...
tip             2.118644
gmo             1.700680
toxic           0.000000
iodine          0.000000
corn, soy       0.000000
Name: llm_judgment, Length: 102, dtype: float64

## Prepare Final Dataset

In [4]:
df_merged_results.head()

,search_term,endpoint_type,rank,doc_id,part_number,sku_name,score,negative_intent,llm_judgment,source_file,variant
0,2 hounds design freedom no pull dog harness,l1_hybrid,1,155034,127945,2 Hounds Design Freedom No Pull Nylon Dog Harn...,0.500000,pull,VIOLATION,l1_hybrid_search_results.csv,control
1,2 hounds design freedom no pull dog harness,l1_hybrid,2,148102,120925,"HDP Big Dog No Pull Dog Harness, Red, Large",0.333333,pull,VIOLATION,l1_hybrid_search_results.csv,control
2,2 hounds design freedom no pull dog harness,l1_hybrid,3,1098406,1098406,PetSafe Easy Walk Comfort Reflective No Pull D...,0.250000,pull,UNCLEAR,l1_hybrid_search_results.csv,control
3,2 hounds design freedom no pull dog harness,l1_hybrid,4,1074806,1074806,Joyride Harness Premium Advanced No Pull Dog H...,0.200000,pull,VIOLATION,l1_hybrid_search_results.csv,control
4,2 hounds design freedom no pull dog harness,l1_hybrid,5,304286,277885,"Frisco Basic No Pull Harness, Pink/Gray, XL",0.166667,pull,UNCLEAR,l1_hybrid_search_results.csv,control

In [5]:
# Use merged data directly - no need for separate merge step
df_final = df_merged_results.copy()

if len(df_final) > 0:
    print(f"\nFinal dataset: {len(df_final)} query-product pairs with evaluations")
    print(f"Unique queries: {df_final['search_term'].nunique()}")
    print(f"Unique products: {df_final['part_number'].nunique()}")
    print(f"Endpoint distribution:")
    print(df_final['endpoint_type'].value_counts())

    # Show sample of final data
    print(f"\nSample data:")
    sample_cols = ['search_term', 'endpoint_type', 'rank', 'sku_name', 'negative_intent', 'llm_judgment']
    available_cols = [col for col in sample_cols if col in df_final.columns]
    print(df_final[available_cols].head())
else:
    print("No data available for analysis")

Final dataset: 111962 query-product pairs with evaluations
Unique queries: 795
Unique products: 14032
Endpoint distribution:
endpoint_type
knn          28609
l1_hybrid    28465
l2           28465
lexical      26423
Name: count, dtype: int64

Sample data:
                                   search_term endpoint_type  rank  \
0  2 hounds design freedom no pull dog harness     l1_hybrid     1
1  2 hounds design freedom no pull dog harness     l1_hybrid     2
2  2 hounds design freedom no pull dog harness     l1_hybrid     3
3  2 hounds design freedom no pull dog harness     l1_hybrid     4
4  2 hounds design freedom no pull dog harness     l1_hybrid     5

                                            sku_name negative_intent  \
0  2 Hounds Design Freedom No Pull Nylon Dog Harn...            pull
1        HDP Big Dog No Pull Dog Harness, Red, Large            pull
2  PetSafe Easy Walk Comfort Reflective No Pull D...            pull
3  Joyride Harness Premium Advanced No Pull Dog H...            pull
4        Frisco Basic No Pull Harness, Pink/Gray, XL            pull

  llm_judgment
0    VIOLATION
1    VIOLATION
2      UNCLEAR
3    VIOLATION
4      UNCLEAR

## Search Term Analysis by Negative Intent

In [6]:
df_final.head()

,search_term,endpoint_type,rank,doc_id,part_number,sku_name,score,negative_intent,llm_judgment,source_file,variant
0,2 hounds design freedom no pull dog harness,l1_hybrid,1,155034,127945,2 Hounds Design Freedom No Pull Nylon Dog Harn...,0.500000,pull,VIOLATION,l1_hybrid_search_results.csv,control
1,2 hounds design freedom no pull dog harness,l1_hybrid,2,148102,120925,"HDP Big Dog No Pull Dog Harness, Red, Large",0.333333,pull,VIOLATION,l1_hybrid_search_results.csv,control
2,2 hounds design freedom no pull dog harness,l1_hybrid,3,1098406,1098406,PetSafe Easy Walk Comfort Reflective No Pull D...,0.250000,pull,UNCLEAR,l1_hybrid_search_results.csv,control
3,2 hounds design freedom no pull dog harness,l1_hybrid,4,1074806,1074806,Joyride Harness Premium Advanced No Pull Dog H...,0.200000,pull,VIOLATION,l1_hybrid_search_results.csv,control
4,2 hounds design freedom no pull dog harness,l1_hybrid,5,304286,277885,"Frisco Basic No Pull Harness, Pink/Gray, XL",0.166667,pull,UNCLEAR,l1_hybrid_search_results.csv,control

In [7]:
def analyze_search_terms_by_intent(df, k=DEFAULT_K):
    """Analyze search terms for each negative intent type"""
    
    if len(df) == 0:
        print("No data available for search term analysis")
        return
    
    # Filter to top K results
    top_k_data = df[df['rank'] <= k].copy()
    
    print(f"=== SEARCH TERM ANALYSIS BY NEGATIVE INTENT (K={k}) ===")
    
    for intent in df['negative_intent'].dropna().unique():
        intent_data = top_k_data[top_k_data['negative_intent'] == intent]
        
        if len(intent_data) == 0:
            continue
            
        print(f"\n--- NEGATIVE INTENT: '{intent}' ---")
        print(f"Total pairs: {len(intent_data)}")
        
        # Violation rate for this intent
        clear_judgments = intent_data[intent_data['llm_judgment'].isin(['VIOLATION', 'COMPLIANT'])]
        if len(clear_judgments) > 0:
            violation_rate = (clear_judgments['llm_judgment'] == 'VIOLATION').mean() * 100
            print(f"Violation rate: {violation_rate:.1f}%")
        
        # Top search terms for this intent
        top_queries = intent_data['search_term'].value_counts().head(5)
        print(f"\nTop search terms:")
        for query, count in top_queries.items():
            query_data = intent_data[intent_data['search_term'] == query]
            violations = (query_data['llm_judgment'] == 'VIOLATION').sum()
            total = len(query_data[query_data['llm_judgment'].isin(['VIOLATION', 'COMPLIANT'])])
            viol_rate = (violations / total * 100) if total > 0 else 0
            print(f"  '{query}' - {count} results, {violations}/{total} violations ({viol_rate:.1f}%)")
        
        # Examples of violations and compliant results
        violations = intent_data[intent_data['llm_judgment'] == 'VIOLATION']
        compliant = intent_data[intent_data['llm_judgment'] == 'COMPLIANT']
        
        if len(violations) > 0:
            print(f"\nExample VIOLATIONS:")
            for i, (idx, row) in enumerate(violations.head(2).iterrows()):
                product_name = row.get('sku_name', 'N/A')[:60]
                print(f"  {i+1}. '{row['search_term']}' → '{product_name}...'")
        
        if len(compliant) > 0:
            print(f"\nExample COMPLIANT:")
            for i, (idx, row) in enumerate(compliant.head(2).iterrows()):
                product_name = row.get('sku_name', 'N/A')[:60]
                print(f"  {i+1}. '{row['search_term']}' → '{product_name}...'")

# Run search term analysis
if len(df_final) > 0:
    analyze_search_terms_by_intent(df_final)
else:
    print("No data available for analysis")

=== SEARCH TERM ANALYSIS BY NEGATIVE INTENT (K=36) ===

--- NEGATIVE INTENT: 'pull' ---
Total pairs: 7259
Violation rate: 36.8%

Top search terms:
  'no pull collars' - 144 results, 68/143 violations (47.6%)
  'no pull collar' - 144 results, 98/141 violations (69.5%)
  'adjustable no pull harness' - 144 results, 132/135 violations (97.8%)
  'no pull dog collar' - 144 results, 47/139 violations (33.8%)
  'no pull dog harness' - 144 results, 22/144 violations (15.3%)

Example VIOLATIONS:
  1. '2 hounds design freedom no pull dog harness' → '2 Hounds Design Freedom No Pull Nylon Dog Harness & Leash, T...'
  2. '2 hounds design freedom no pull dog harness' → 'HDP Big Dog No Pull Dog Harness, Red, Large...'

Example COMPLIANT:
  1. '2 hounds design freedom no pull dog harness' → 'Gooby Escape Free Comfort X One Dog Harness, Portland Green,...'
  2. 'adjustable no pull harness' → 'Sporn Original No Pull Training Halter Dog Harness, Blue, La...'

--- NEGATIVE INTENT: 'grain' ---
Total pairs: 47104
Violation rate: 18.3%

Top search terms:
  'acana grain free' - 144 results, 33/143 violations (23.1%)
  'hills science grain free' - 144 results, 120/144 violations (83.3%)
  'iams grain free cat food' - 144 results, 73/142 violations (51.4%)
  'honest kitchen grain free dog food' - 144 results, 52/143 violations (36.4%)
  'honest kitchen grain free dehydrated dog food' - 144 results, 60/140 violations (42.9%)

Example VIOLATIONS:
  1. 'acana grain free' → 'ACANA Free-Run Poultry Wholesome Grains Dry Dog Food, 4-lb b...'
  2. 'acana grain free' → 'ACANA Wholesome Grains Puppy Sea & Farm Dry Dog Food, 4-lb b...'

Example COMPLIANT:
  1. 'acana grain free' → 'ACANA Singles Beef & Pumpkin Grain-Free Limited Ingredients ...'
  2. 'acana grain free' → 'ACANA Singles Lamb & Apple Grain-Free Limited Ingredients & ...'

--- NEGATIVE INTENT: 'aller' ---
Total pairs: 109
Violation rate: 38.6%

Top search terms:
  'aller free' - 109 results, 39/101 violations (38.6%)

Example VIOLATIONS:
  1. 'aller free' → 'Zesty Paws Allergy & Immune Bites Salmon Flavored Soft Chews...'
  2. 'aller free' → 'Nootie Progility Allergy & Immune for Seasonal Allergies Sof...'

Example COMPLIANT:
  1. 'aller free' → 'Wholesomes Sensitive Skin & Stomach with Salmon Protein Dry ...'
  2. 'aller free' → 'Wellness Complete Health Sensitive Skin & Stomach Natural Ad...'

--- NEGATIVE INTENT: 'allergy' ---
Total pairs: 434
Violation rate: 18.1%

Top search terms:
  'allergy free cat food' - 144 results, 27/137 violations (19.7%)
  'allergy free dog food' - 144 results, 17/139 violations (12.2%)
  'allergy free dog treats' - 144 results, 28/120 violations (23.3%)
  'aller free' - 2 results, 0/1 violations (0.0%)

Example VIOLATIONS:
  1. 'allergy free cat food' → 'Whole Life Nature's Remedy Skin & Allergy Support Whole Food...'
  2. 'allergy free cat food' → 'Purina ONE LiveClear Allergen-Reducing Formula Chicken Flavo...'

Example COMPLIANT:
  1. 'allergy free cat food' → 'Blue Buffalo Wilderness Salmon Recipe Grain-Free Dry Cat Foo...'
  2. 'allergy free cat food' → 'Halo Holistic Indoor Wild-Caught Salmon & Whitefish Recipe C...'

--- NEGATIVE INTENT: 'waste free' ---
Total pairs: 110
Violation rate: 30.9%

Top search terms:
  'audubon park waste free' - 110 results, 34/110 violations (30.9%)

Example VIOLATIONS:
  1. 'audubon park waste free' → 'Audubon Park Waste Free Wild Bird Food, 15-lb bag...'
  2. 'audubon park waste free' → 'Audubon Park No Waste Blend Wild Bird Food, 5-lb bag...'

Example COMPLIANT:
  1. 'audubon park waste free' → 'Audubon Park Nut & Fruit Seed Blends Wild Bird Food, 5-lb ba...'
  2. 'audubon park waste free' → 'Audubon Park Songbird Seed Blend Wild Bird Food, 4.5-lb bag...'

--- NEGATIVE INTENT: 'shock' ---
Total pairs: 720
Violation rate: 84.0%

Top search terms:
  'bark collar no shock' - 144 results, 82/97 violations (84.5%)
  'no shock bark collar' - 144 results, 82/98 violations (83.7%)
  'no shock collar' - 144 results, 110/134 violations (82.1%)
  'no shock dog collar' - 144 results, 113/128 violations (88.3%)
  'no shock training collar' - 144 results, 95/117 violations (81.2%)

Example VIOLATIONS:
  1. 'bark collar no shock' → 'PATPET A12 Waterproof Electronic Smart Shock Training Dog Co...'
  2. 'bark collar no shock' → 'PATPET P301 1000ft Remote Dog Bark Control & Training Shock ...'

Example COMPLIANT:
  1. 'bark collar no shock' → 'PATPET No Shock Smart Bark Control Dog Bark Collar...'
  2. 'bark collar no shock' → 'No Shock Rechargeable Bark Collar, Grey...'

--- NEGATIVE INTENT: 'odor' ---
Total pairs: 1440
Violation rate: 12.2%

Top search terms:
  'barkworthies odor free bully sticks' - 144 results, 64/128 violations (50.0%)
  'best bully sticks odor free' - 144 results, 2/142 violations (1.4%)
  'bully stick odor free' - 144 results, 12/144 violations (8.3%)
  'bully sticks for dogs odor free' - 144 results, 3/142 violations (2.1%)
  'bully sticks odor free' - 144 results, 9/144 violations (6.2%)

Example VIOLATIONS:
  1. 'barkworthies odor free bully sticks' → 'Best Bully Sticks Odor Free 6" Bully Stick Dog Treats, 6 cou...'
  2. 'barkworthies odor free bully sticks' → 'Barkworthies American 6" Bully Sticks Dog Treat...'

Example COMPLIANT:
  1. 'barkworthies odor free bully sticks' → 'Barkworthies Odor-Free 6" Bully Sticks, 5 pack...'
  2. 'barkworthies odor free bully sticks' → 'Barkworthies Odor-Free Standard 6" Bully Sticks Dog Treat...'

--- NEGATIVE INTENT: 'mess' ---
Total pairs: 1985
Violation rate: 8.1%

Top search terms:
  'bird food wild no mess' - 144 results, 10/81 violations (12.3%)
  'bird seed no mess' - 144 results, 5/80 violations (6.2%)
  'bird seed wild no mess' - 144 results, 17/85 violations (20.0%)
  'kaytee no mess blend wild bird food' - 144 results, 17/98 violations (17.3%)
  'kaytee wild bird food no mess' - 144 results, 12/54 violations (22.2%)

Example VIOLATIONS:
  1. 'bird food wild no mess' → 'Schoen Farms Less Mess Wild Bird Food Mix, 5-lb bag...'
  2. 'bird food wild no mess' → 'Kaytee Wild Finch Wild Bird Food, 5-lb bag...'

Example COMPLIANT:
  1. 'bird food wild no mess' → 'Kaytee No Mess Blend Wild Bird Food, 10-lb bag...'
  2. 'bird food wild no mess' → 'Audubon Park No Waste Blend Wild Bird Food, 14-lb bag...'

--- NEGATIVE INTENT: 'waste' ---
Total pairs: 1296
Violation rate: 8.3%

Top search terms:
  'bird seed no waste' - 144 results, 2/96 violations (2.1%)
  'bird seed wild no waste' - 144 results, 12/112 violations (10.7%)
  'no waste bird food' - 144 results, 4/124 violations (3.2%)
  'no waste bird seed' - 144 results, 1/107 violations (0.9%)
  'no waste wild bird food' - 144 results, 10/123 violations (8.1%)

Example VIOLATIONS:
  1. 'bird seed no waste' → 'Valley Splendor Nut & Fruit Seeds Wild Bird Food, 4-lb bag...'
  2. 'bird seed wild no waste' → 'Melody Select Waste Free Nut & Fruit Bird Food, 5-lb bag...'

Example COMPLIANT:
  1. 'bird seed no waste' → 'Better Bird Zero-Waste Bird Food, 5-lb bag...'
  2. 'bird seed no waste' → 'Melody Select Waste Free Nut & Fruit Bird Food, 5-lb bag...'

--- NEGATIVE INTENT: 'melt' ---
Total pairs: 579
Violation rate: 8.8%

Top search terms:
  'bird suet cakes no melt' - 144 results, 14/49 violations (28.6%)
  'no melt suet cakes for birds' - 144 results, 0/52 violations (0.0%)
  'no melt suet cakes for wild birds' - 144 results, 0/47 violations (0.0%)
  'suet cakes for wild birds no melt' - 144 results, 3/45 violations (6.7%)
  'no melt suet' - 3 results, 0/0 violations (0.0%)

Example VIOLATIONS:
  1. 'bird suet cakes no melt' → 'Pine Tree Farms Never Melt Suet Insect Cake Bird Food, 12-oz...'
  2. 'bird suet cakes no melt' → 'Pine Tree Farms Never Melt Suet Hot Pepper Cake Bird Food, 1...'

Example COMPLIANT:
  1. 'bird suet cakes no melt' → 'C&S Peanut Delight No Melt Suet Dough Wild Bird Food, 11.75-...'
  2. 'bird suet cakes no melt' → 'C&S Hot Pepper Delight No Melt Suet Dough Wild Bird Food, 11...'

--- NEGATIVE INTENT: 'chicken' ---
Total pairs: 8433
Violation rate: 80.3%

Top search terms:
  'blue buffalo chicken free' - 144 results, 117/141 violations (83.0%)
  'chicken-free wet dog food' - 144 results, 86/122 violations (70.5%)
  'dog food no chicken' - 144 results, 91/137 violations (66.4%)
  'dog food with no chicken' - 144 results, 72/121 violations (59.5%)
  'dog treats chicken free' - 144 results, 127/132 violations (96.2%)

Example VIOLATIONS:
  1. 'blue buffalo chicken free' → 'Blue Buffalo Freedom Complete & Balanced Nutrition Adult Gra...'
  2. 'blue buffalo chicken free' → 'Blue Buffalo Freedom Healthy Weight Adult Grain-Free Chicken...'

Example COMPLIANT:
  1. 'blue buffalo chicken free' → 'Blue Buffalo Freedom Adult Grain-Free Lamb & Potatoes Dry Do...'
  2. 'blue buffalo chicken free' → 'Blue Buffalo Blue Bits Tender Beef Recipe Chicken-Free Soft-...'

--- NEGATIVE INTENT: 'bpa' ---
Total pairs: 144

Top search terms:
  'bpa free litter box' - 144 results, 0/0 violations (0.0%)

--- NEGATIVE INTENT: 'd3' ---
Total pairs: 144
Violation rate: 59.3%

Top search terms:
  'calcium without d3' - 144 results, 51/86 violations (59.3%)

Example VIOLATIONS:
  1. 'calcium without d3' → 'Zoo Med Repti Calcium with D3 Reptile Supplement, 48-oz jar...'
  2. 'calcium without d3' → 'Fluker's Calcium with Vitamin D3 Indoor Reptile Supplement, ...'

Example COMPLIANT:
  1. 'calcium without d3' → 'Zoo Med Repti Calcium without D3 Reptile Supplement, 8-oz ja...'
  2. 'calcium without d3' → 'Fluker's Calcium without Vitamin D3 Outdoor Reptile Suppleme...'

--- NEGATIVE INTENT: 'hide' ---
Total pairs: 5050
Violation rate: 25.7%

Top search terms:
  'canine naturals hide free' - 144 results, 61/131 violations (46.6%)
  'no hide chews large' - 144 results, 35/143 violations (24.5%)
  'no hide stix' - 144 results, 37/142 violations (26.1%)
  'no hide sticks' - 144 results, 28/140 violations (20.0%)
  'no hide small rolls' - 144 results, 28/144 violations (19.4%)

Example VIOLATIONS:
  1. 'canine naturals hide free' → 'Canine Naturals Hide Free 5-inch Beef Flavor Stick Dog Chew,...'
  2. 'canine naturals hide free' → 'Canine Naturals Hide-Free Puppy Sticks Chicken Dog Treat, 40...'

Example COMPLIANT:
  1. 'canine naturals hide free' → 'Canine Naturals Hide Free Chicken Recipe Stick Dog Chew, 40 ...'
  2. 'canine naturals hide free' → 'Canine Naturals Hide Free Chicken Recipe Roll Dog Chew, 2 co...'

--- NEGATIVE INTENT: 'bell' ---
Total pairs: 144
Violation rate: 100.0%

Top search terms:
  'cat collar no bell' - 144 results, 139/139 violations (100.0%)

Example VIOLATIONS:
  1. 'cat collar no bell' → 'Necoichi Chirimen Fireworks Breakaway Cat Collar with Bell, ...'
  2. 'cat collar no bell' → 'Pawtitas Nylon Reflective Breakaway Cat Collar with Bell, Gr...'

--- NEGATIVE INTENT: 'prescription' ---
Total pairs: 276
Violation rate: 45.5%

Top search terms:
  'cat dewormer no prescription' - 144 results, 58/96 violations (60.4%)
  'non prescription pain meds for dogs' - 112 results, 36/105 violations (34.3%)
  'non prescription flea meds' - 12 results, 3/12 violations (25.0%)
  'non prescription flea medicine' - 8 results, 3/7 violations (42.9%)

Example VIOLATIONS:
  1. 'cat dewormer no prescription' → 'Revolution Topical Solution for Cats, 5.1-15 lbs, (Blue Box)...'
  2. 'cat dewormer no prescription' → 'Drontal Tablets for Cats & Kittens, 2-16 lbs, 1 Tablet...'

Example COMPLIANT:
  1. 'cat dewormer no prescription' → 'Elanco Dewormer for Tapeworms for Cats, 3 count...'
  2. 'cat dewormer no prescription' → 'HomeoPet WRM Clear Dewormer for Hookworms, Roundworms, Tapew...'

--- NEGATIVE INTENT: 'additives' ---
Total pairs: 114
Violation rate: 100.0%

Top search terms:
  'cat food with no additives' - 114 results, 20/20 violations (100.0%)

Example VIOLATIONS:
  1. 'cat food with no additives' → 'Purina Cat Chow Naturals Original with Added Vitamins, Miner...'
  2. 'cat food with no additives' → 'Oratene Enzymatic Brushless Oral Care Dog & Cat Dental Water...'

--- NEGATIVE INTENT: 'dust' ---
Total pairs: 2014
Violation rate: 28.7%

Top search terms:
  'cat litter dust free' - 144 results, 13/38 violations (34.2%)
  'cat litter no dust' - 144 results, 14/39 violations (35.9%)
  'clumping cat litter dust free' - 144 results, 25/41 violations (61.0%)
  'dust free cat litter' - 144 results, 5/38 violations (13.2%)
  'dust free clumping cat litter' - 144 results, 14/25 violations (56.0%)

Example VIOLATIONS:
  1. 'cat litter dust free' → 'Arm & Hammer Litter Clump & Seal Multi-Cat Scented Clumping ...'
  2. 'cat litter dust free' → 'Tidy Cats Instant Action Non-Clumping Clay Cat Litter, 10-lb...'

Example COMPLIANT:
  1. 'cat litter dust free' → 'PetSafe ScoopFree Premium Crystal Cat Litter 2-Pack, Blue...'
  2. 'cat litter dust free' → 'PACO & PEPPER Made from Olive Pits 0% Dust Natural Unscented...'

--- NEGATIVE INTENT: 'fragrance' ---
Total pairs: 432
Violation rate: 47.4%

Top search terms:
  'cat litter fragrance free' - 144 results, 60/132 violations (45.5%)
  'fragrance free cat litter' - 144 results, 50/124 violations (40.3%)
  'fragrance free dog shampoo' - 144 results, 46/73 violations (63.0%)

Example VIOLATIONS:
  1. 'cat litter fragrance free' → 'Fresh Step Premium Scented Non-Clumping Cat Litter, 14-lb...'
  2. 'cat litter fragrance free' → 'NonScents Cat Litter Deodorizer, 14-fl oz bottle...'

Example COMPLIANT:
  1. 'cat litter fragrance free' → 'PetSafe ScoopFree Crystal Cat Litter Box Tray Refill with Fr...'
  2. 'cat litter fragrance free' → 'Fresh Kitty Fragrance-Free Cat Litter Deodorizer, 20-oz pouc...'

--- NEGATIVE INTENT: 'scent' ---
Total pairs: 466
Violation rate: 75.8%

Top search terms:
  'cat litter no scent' - 144 results, 117/138 violations (84.8%)
  'scent free cat litter' - 144 results, 95/125 violations (76.0%)
  'scent free litter' - 144 results, 95/130 violations (73.1%)
  'unscented dust free clumping cat litter' - 15 results, 0/14 violations (0.0%)
  'non scented litter' - 9 results, 8/9 violations (88.9%)

Example VIOLATIONS:
  1. 'cat litter no scent' → 'Fresh Step Febreze Freshness Gain Scented Clumping Clay Cat ...'
  2. 'cat litter no scent' → 'Tidy Cats Lightweight with Glade Scented Clumping Clay Cat L...'

Example COMPLIANT:
  1. 'cat litter no scent' → 'Scoop Away Clumping Unscented Cat Litter, 25-lb box...'
  2. 'scent free cat litter' → 'PetSafe ScoopFree Premium Crystal Cat Litter 2-Pack, Sensiti...'

--- NEGATIVE INTENT: 'tracking' ---
Total pairs: 731
Violation rate: 47.9%

Top search terms:
  'cat litter no tracking' - 144 results, 46/73 violations (63.0%)
  'no tracking cat litter' - 144 results, 60/77 violations (77.9%)
  'no tracking litter' - 144 results, 59/92 violations (64.1%)
  'non tracking cat litter' - 144 results, 25/105 violations (23.8%)
  'non tracking litter' - 144 results, 31/118 violations (26.3%)

Example VIOLATIONS:
  1. 'cat litter no tracking' → 'Cat's Pride Max Power UltraClean Low-Tracking Multi-Cat Clum...'
  2. 'cat litter no tracking' → 'Cat's Pride Max Power UltraClean Low-Tracking Multi-Cat Clum...'

Example COMPLIANT:
  1. 'cat litter no tracking' → 'Fresh Step Clean Paws Multi-Cat Scented Clumping Cat Litter,...'
  2. 'cat litter no tracking' → 'Naturally Fresh Unscented Clumping Walnut Cat Litter, 14-lb ...'

--- NEGATIVE INTENT: 'pee' ---
Total pairs: 291
Violation rate: 80.7%

Top search terms:
  'cat no pee' - 144 results, 101/144 violations (70.1%)
  'no pee' - 144 results, 132/143 violations (92.3%)
  'no cat pee' - 3 results, 1/3 violations (33.3%)

Example VIOLATIONS:
  1. 'cat no pee' → 'Nature's Miracle Cat Urine Destroyer Plus Enzymatic Formula ...'
  2. 'cat no pee' → 'Stink Free Cat Urine & Odor Remover, 32-fl oz bottle...'

Example COMPLIANT:
  1. 'cat no pee' → 'NaturVet Pet Organics No Mark! Stops Cats' Desire to Urine M...'
  2. 'cat no pee' → 'Sentry Stop That! Noise & Pheromone Cat Spray, 1-fl oz...'

--- NEGATIVE INTENT: 'scratch' ---
Total pairs: 522
Violation rate: 75.3%

Top search terms:
  'cat no scratch' - 144 results, 135/144 violations (93.8%)
  'no scratch' - 144 results, 143/144 violations (99.3%)
  'no scratch spray' - 118 results, 63/114 violations (55.3%)
  'no scratch spray for cats' - 116 results, 46/112 violations (41.1%)

Example VIOLATIONS:
  1. 'cat no scratch' → 'Emmy's Best Pet Products Stop the Scratch Max Strength Cat S...'
  2. 'cat no scratch' → 'TRIXIE Parla 24.4-in Fleece Cat Scratching Post, Platinum Gr...'

Example COMPLIANT:
  1. 'cat no scratch' → 'NaturVet Pet Organics No Scratch for Cats, 16-fl oz bottle...'
  2. 'cat no scratch' → 'Stella & Chewy's Chicken Flavored Raw Coated Cage Free Dry C...'

--- NEGATIVE INTENT: 'catnip' ---
Total pairs: 188
Violation rate: 100.0%

Top search terms:
  'cat toys no catnip' - 144 results, 142/142 violations (100.0%)
  'cat toys without catnip' - 44 results, 41/41 violations (100.0%)

Example VIOLATIONS:
  1. 'cat toys no catnip' → 'Potaroma Catnip Crinkle Kicker Plush Cat Toy, 3 count...'
  2. 'cat toys no catnip' → 'Yeowww! Catnip Yellow Banana Cat Toy...'

--- NEGATIVE INTENT: 'carpet' ---
Total pairs: 144
Violation rate: 94.2%

Top search terms:
  'cat tree no carpet' - 144 results, 81/86 violations (94.2%)

Example VIOLATIONS:
  1. 'cat tree no carpet' → 'Frisco 69-in Real Carpet Solid Wood Cat Tree, Beige...'
  2. 'cat tree no carpet' → 'Frisco 65-in Real Carpet Solid Wood Cat Tree, Gray...'

Example COMPLIANT:
  1. 'cat tree no carpet' → 'Yaheetech 36-in Rattan Cat Tree, Beige...'
  2. 'cat tree no carpet' → 'Yaheetech 36-in Rattan Cat Tree, Beige...'

--- NEGATIVE INTENT: 'rawhide' ---
Total pairs: 6737
Violation rate: 25.4%

Top search terms:
  'chew bones rawhide free' - 144 results, 30/141 violations (21.3%)
  'rawhide free' - 144 results, 13/141 violations (9.2%)
  'non rawhide dog chews' - 144 results, 16/139 violations (11.5%)
  'non rawhide dog treats' - 144 results, 29/136 violations (21.3%)
  'pork chomps rawhide free' - 144 results, 0/144 violations (0.0%)

Example VIOLATIONS:
  1. 'chew bones rawhide free' → 'DreamBone Twist Sticks Real Chicken Rawhide Free Dog Chews, ...'
  2. 'chew bones rawhide free' → 'DreamBone Real Chicken Rawhide Free Dog Chew Bones, Small, 6...'

Example COMPLIANT:
  1. 'chew bones rawhide free' → 'Milk-Bone Flavor Rolls Beefy Cheesy, Yes Please-y! Rawhide F...'
  2. 'chew bones rawhide free' → 'Milk-Bone Flavor Rolls Chicken Doodle Dandy Rawhide Free wit...'

--- NEGATIVE INTENT: 'poo' ---
Total pairs: 575
Violation rate: 53.3%

Top search terms:
  'chew no poo' - 144 results, 104/144 violations (72.2%)
  'no poo' - 144 results, 93/144 violations (64.6%)
  'no poo chews' - 144 results, 41/144 violations (28.5%)
  'no poo chews for dogs' - 143 results, 68/142 violations (47.9%)

Example VIOLATIONS:
  1. 'chew no poo' → 'Zesty Paws Chew No Poo Chicken Flavored Soft Chews Coprophag...'
  2. 'chew no poo' → 'Chew + Heal Stop The Poo Peanut Butter Flavored Soft Chew Co...'

Example COMPLIANT:
  1. 'chew no poo' → 'Chew + Heal Stop The Diarrhea Liquid Digestive Aid for Dogs,...'
  2. 'chew no poo' → 'Chew + Heal Max Protect X-Large Pee Travel Pack Dog Potty Pa...'

--- NEGATIVE INTENT: 'poop' ---
Total pairs: 566
Violation rate: 61.2%

Top search terms:
  'chew no poop' - 144 results, 108/143 violations (75.5%)
  'no poop' - 144 results, 107/144 violations (74.3%)
  'no poop chews' - 144 results, 59/144 violations (41.0%)
  'no eat poop' - 123 results, 68/122 violations (55.7%)
  'no poop eating' - 11 results, 3/11 violations (27.3%)

Example VIOLATIONS:
  1. 'chew no poop' → 'Chew + Heal Stop The Poo Peanut Butter Flavored Soft Chew Co...'
  2. 'chew no poop' → 'Zesty Paws Chew No Poo Chicken Flavored Soft Chews Coprophag...'

Example COMPLIANT:
  1. 'chew no poop' → 'Earth Animal No-Hide Small Rolls Long Lasting Natural Rawhid...'
  2. 'chew no poop' → 'Chew + Heal No Chew Dog & Cat Spray, 8-fl oz bottle...'

--- NEGATIVE INTENT: 'medicated' ---
Total pairs: 128
Violation rate: 37.6%

Top search terms:

## L1 Metrics: Retrieval-Path Level Analysis

In [8]:
def calculate_l1_metrics(df, k_values=K_VALUES):
    """Calculate L1 metrics per retrieval path - both per search term and aggregated"""
    
    if len(df) == 0:
        return {}
    
    l1_metrics = {}
    
    for endpoint in df['endpoint_type'].unique():
        endpoint_data = df[df['endpoint_type'] == endpoint].copy()
        endpoint_metrics = {}
        
        for k in k_values:
            # Filter to top K results per query
            top_k = endpoint_data[endpoint_data['rank'] <= k].copy()
            
            if len(top_k) == 0:
                continue
            
            # Calculate per-search-term metrics first
            search_term_metrics = []
            search_term_details = {}
            
            for search_term in top_k['search_term'].unique():
                term_data = top_k[top_k['search_term'] == search_term]
                
                # Calculate metrics for this search term
                total_results = len(term_data)
                violation_count = len(term_data[term_data['llm_judgment'] == 'VIOLATION'])
                compliant_count = len(term_data[term_data['llm_judgment'] == 'COMPLIANT'])
                unclear_count = len(term_data[term_data['llm_judgment'] == 'UNCLEAR'])
                
                term_violation_rate = violation_count / total_results if total_results > 0 else 0
                term_compliant_rate = compliant_count / total_results if total_results > 0 else 0
                term_unclear_rate = unclear_count / total_results if total_results > 0 else 0
                
                # Store individual search term details
                search_term_details[search_term] = {
                    f'violation_rate@{k}': term_violation_rate,
                    f'compliant_rate@{k}': term_compliant_rate,
                    f'unclear_rate@{k}': term_unclear_rate,
                    'total_results': total_results,
                    'violation_count': violation_count,
                    'compliant_count': compliant_count,
                    'unclear_count': unclear_count
                }
                
                # Collect for aggregation
                search_term_metrics.append({
                    f'violation_rate@{k}': term_violation_rate,
                    f'compliant_rate@{k}': term_compliant_rate,
                    f'unclear_rate@{k}': term_unclear_rate
                })
            
            # Calculate aggregated metrics (average across search terms)
            if search_term_metrics:
                agg_violation_rate = sum(m[f'violation_rate@{k}'] for m in search_term_metrics) / len(search_term_metrics)
                agg_compliant_rate = sum(m[f'compliant_rate@{k}'] for m in search_term_metrics) / len(search_term_metrics)
                agg_unclear_rate = sum(m[f'unclear_rate@{k}'] for m in search_term_metrics) / len(search_term_metrics)
            else:
                agg_violation_rate = agg_compliant_rate = agg_unclear_rate = None
            
            endpoint_metrics[f'K{k}'] = {
                # Aggregated metrics (average across search terms)
                f'violation_rate@{k}': agg_violation_rate,
                f'compliant_rate@{k}': agg_compliant_rate,
                f'unclear_rate@{k}': agg_unclear_rate,
                # Summary counts
                'total_search_terms': len(search_term_metrics),
                # Individual search term details
                'search_term_details': search_term_details
            }
        
        l1_metrics[endpoint] = endpoint_metrics
    
    return l1_metrics

# Calculate L1 metrics
if len(df_final) > 0:
    l1_metrics = calculate_l1_metrics(df_final)
    
    # Display L1 results
    print("\n=== L1 METRICS (Per Retrieval Path) ===")
    for endpoint, metrics in l1_metrics.items():
        print(f"\n{endpoint.upper()} ENDPOINT:")
        for k_level, k_metrics in metrics.items():
            k_val = k_level.replace('K', '')  # Extract K value
            print(f"\n  {k_level}:")
            print(f"    Violation Rate@{k_val}: {k_metrics[f'violation_rate@{k_val}']:.3f}, "
                  f"Compliant Rate@{k_val}: {k_metrics[f'compliant_rate@{k_val}']:.3f}, "
                  f"UNCLEAR Rate@{k_val}: {k_metrics[f'unclear_rate@{k_val}']:.3f}")
            print(f"    ({k_metrics['total_search_terms']} search terms)")
            
            # Show top/bottom search terms by violation rate
            term_details = k_metrics['search_term_details']
            sorted_terms = sorted(term_details.items(), key=lambda x: x[1][f'violation_rate@{k_val}'], reverse=True)
            
            print(f"\n  {k_level} - TOP 3 HIGHEST VIOLATION SEARCH TERMS:")
            for i, (term, details) in enumerate(sorted_terms[:3]):
                print(f"    {i+1}. '{term}': {details[f'violation_rate@{k_val}']:.3f} "
                      f"({details['violation_count']}/{details['total_results']})")
            
            print(f"\n  {k_level} - TOP 3 LOWEST VIOLATION SEARCH TERMS:")
            for i, (term, details) in enumerate(sorted_terms[-3:]):
                print(f"    {i+1}. '{term}': {details[f'violation_rate@{k_val}']:.3f} "
                      f"({details['violation_count']}/{details['total_results']})")

=== L1 METRICS (Per Retrieval Path) ===

L1_HYBRID ENDPOINT:

  K4:
    Violation Rate@4: 0.277, Compliant Rate@4: 0.665, UNCLEAR Rate@4: 0.058
    (795 search terms)

  K4 - TOP 3 HIGHEST VIOLATION SEARCH TERMS:
    1. 'beneful grain free': 1.000 (4/4)
    2. 'best no pull harness': 1.000 (4/4)
    3. 'blue buffalo chicken free': 1.000 (4/4)

  K4 - TOP 3 LOWEST VIOLATION SEARCH TERMS:
    1. 'wheat free puppy food': 0.000 (0/4)
    2. 'wholesomes grain free dog food': 0.000 (0/4)
    3. 'wild bird seed no waste': 0.000 (0/4)

  K10:
    Violation Rate@10: 0.281, Compliant Rate@10: 0.646, UNCLEAR Rate@10: 0.073
    (795 search terms)

  K10 - TOP 3 HIGHEST VIOLATION SEARCH TERMS:
    1. 'blue buffalo chicken free': 1.000 (10/10)
    2. 'cat collar no bell': 1.000 (10/10)
    3. 'cat litter no scent': 1.000 (10/10)

  K10 - TOP 3 LOWEST VIOLATION SEARCH TERMS:
    1. 'wheat free dog treats': 0.000 (0/10)
    2. 'wheat free puppy food': 0.000 (0/10)
    3. 'wild bird seed no waste': 0.000 (0/10)

  K36:
    Violation Rate@36: 0.284, Compliant Rate@36: 0.606, UNCLEAR Rate@36: 0.110
    (795 search terms)

  K36 - TOP 3 HIGHEST VIOLATION SEARCH TERMS:
    1. 'cat toys no catnip': 1.000 (36/36)
    2. 'cat toys without catnip': 1.000 (4/4)
    3. 'chicken free wet cat food': 1.000 (36/36)

  K36 - TOP 3 LOWEST VIOLATION SEARCH TERMS:
    1. 'wheat free cat food': 0.000 (0/36)
    2. 'wheat free dog food': 0.000 (0/36)
    3. 'wild bird seed no waste': 0.000 (0/36)

L2 ENDPOINT:

  K4:
    Violation Rate@4: 0.275, Compliant Rate@4: 0.665, UNCLEAR Rate@4: 0.060
    (795 search terms)

  K4 - TOP 3 HIGHEST VIOLATION SEARCH TERMS:
    1. 'beneful grain free': 1.000 (4/4)
    2. 'best no pull harness': 1.000 (4/4)
    3. 'blue buffalo chicken free': 1.000 (4/4)

  K4 - TOP 3 LOWEST VIOLATION SEARCH TERMS:
    1. 'wheat free puppy food': 0.000 (0/4)
    2. 'wholesomes grain free dog food': 0.000 (0/4)
    3. 'wild bird seed no waste': 0.000 (0/4)

  K10:
    Violation Rate@10: 0.278, Compliant Rate@10: 0.650, UNCLEAR Rate@10: 0.072
    (795 search terms)

  K10 - TOP 3 HIGHEST VIOLATION SEARCH TERMS:
    1. 'blue buffalo chicken free': 1.000 (10/10)
    2. 'cat collar no bell': 1.000 (10/10)
    3. 'cat litter no scent': 1.000 (10/10)

  K10 - TOP 3 LOWEST VIOLATION SEARCH TERMS:
    1. 'wheat free dog treats': 0.000 (0/10)
    2. 'wheat free puppy food': 0.000 (0/10)
    3. 'wild bird seed no waste': 0.000 (0/10)

  K36:
    Violation Rate@36: 0.283, Compliant Rate@36: 0.607, UNCLEAR Rate@36: 0.110
    (795 search terms)

  K36 - TOP 3 HIGHEST VIOLATION SEARCH TERMS:
    1. 'cat toys no catnip': 1.000 (36/36)
    2. 'cat toys without catnip': 1.000 (4/4)
    3. 'chicken free wet cat food': 1.000 (36/36)

  K36 - TOP 3 LOWEST VIOLATION SEARCH TERMS:
    1. 'wheat free cat food': 0.000 (0/36)
    2. 'wheat free dog food': 0.000 (0/36)
    3. 'wild bird seed no waste': 0.000 (0/36)

KNN ENDPOINT:

  K4:
    Violation Rate@4: 0.255, Compliant Rate@4: 0.676, UNCLEAR Rate@4: 0.069
    (795 search terms)

  K4 - TOP 3 HIGHEST VIOLATION SEARCH TERMS:
    1. 'adjustable no pull harness': 1.000 (4/4)
    2. 'beneful grain free': 1.000 (4/4)
    3. 'blue buffalo chicken free': 1.000 (4/4)

  K4 - TOP 3 LOWEST VIOLATION SEARCH TERMS:
    1. 'wholesome grain free': 0.000 (0/4)
    2. 'wholesomes grain free dog food': 0.000 (0/4)
    3. 'wild bird seed no waste': 0.000 (0/4)

  K10:
    Violation Rate@10: 0.261, Compliant Rate@10: 0.659, UNCLEAR Rate@10: 0.080
    (795 search terms)

  K10 - TOP 3 HIGHEST VIOLATION SEARCH TERMS:
    1. 'adjustable no pull harness': 1.000 (10/10)
    2. 'beneful grain free': 1.000 (10/10)
    3. 'blue buffalo no chicken': 1.000 (10/10)

  K10 - TOP 3 LOWEST VIOLATION SEARCH TERMS:
    1. 'wheat free cat food': 0.000 (0/10)
    2. 'wheat free dog food': 0.000 (0/10)
    3. 'wild bird seed no waste': 0.000 (0/10)

  K36:
    Violation Rate@36: 0.268, Compliant Rate@36: 0.622, UNCLEAR Rate@36: 0.109
    (795 search terms)

  K36 - TOP 3 HIGHEST VIOLATION SEARCH TERMS:
    1. 'adjustable no pull harness': 1.000 (36/36)
    2. 'chicken free wet cat food': 1.000 (36/36)
    3. 'dog harness no escape': 1.000 (36/36)

  K36 - TOP 3 LOWEST VIOLATION SEARCH TERMS:
    1. 'suet cakes for wild birds no melt': 0.000 (0/36)
    2. 'wheat free dog food': 0.000 (0/36)
    3. 'wild bird seed no waste': 0.000 (0/36)

LEXICAL ENDPOINT:

  K4:
    Violation Rate@4: 0.271, Compliant Rate@4: 0.695, UNCLEAR Rate@4: 0.033
    (793 search terms)

  K4 - TOP 3 HIGHEST VIOLATION SEARCH TERMS:
    1. 'adjustable no pull harness': 1.000 (4/4)
    2. 'aller free': 1.000 (3/3)
    3. 'audubon park waste free': 1.000 (2/2)

  K4 - TOP 3 LOWEST VIOLATION SEARCH TERMS:
    1. 'wheat free dog treats': 0.000 (0/4)
    2. 'wheat free puppy food': 0.000 (0/4)
    3. 'wild bird seed no waste': 0.000 (0/4)

  K10:
    Violation Rate@10: 0.281, Compliant Rate@10: 0.669, UNCLEAR Rate@10: 0.050
    (793 search terms)

  K10 - TOP 3 HIGHEST VIOLATION SEARCH TERMS:
    1. 'adjustable no pull harness': 1.000 (10/10)
    2. 'aller free': 1.000 (3/3)
    3. 'audubon park waste free': 1.000 (2/2)

  K10 - TOP 3 LOWEST VIOLATION SEARCH TERMS:
    1. 'wheat free dog treats': 0.000 (0/10)
    2. 'wheat free puppy food': 0.000 (0/10)
    3. 'wild bird seed no waste': 0.000 (0/10)

  K36:
    Violation Rate@36: 0.285, Compliant Rate@36: 0.619, UNCLEAR Rate@36: 0.096
    (793 search terms)

  K36 - TOP 3 HIGHEST VIOLATION SEARCH TERMS:
    1. 'aller free': 1.000 (3/3)
    2. 'audubon park waste free': 1.000 (2/2)
    3. 'cat collar no bell': 1.000 (36/36)

  K36 - TOP 3 LOWEST VIOLATION SEARCH TERMS:
    1. 'wheat free cat food': 0.000 (0/36)
    2. 'wheat free dog treats': 0.000 (0/36)
    3. 'wild bird seed no waste': 0.000 (0/36)

In [9]:
df_final.endpoint_type.unique()

array(['l1_hybrid', 'l2', 'knn', 'lexical'], dtype=object)

In [10]:
l1_metrics.keys()

dict_keys(['l1_hybrid', 'l2', 'knn', 'lexical'])

In [11]:
l1_metrics['l1_hybrid'].keys()

dict_keys(['K4', 'K10', 'K36'])

## L2 Metrics: End-to-End Analysis

In [12]:
# Extract L2 metrics from l1_metrics (already calculated for l2 endpoint)
l2_metrics = l1_metrics.get('l2', {})

if len(df_final) > 0 and len(l2_metrics) > 0:
    # Display L2 results
    print("\n=== L2 METRICS (End-to-End) ===")
    for k_level, k_metrics in l2_metrics.items():
        k_val = k_level.replace('K', '')  # Extract K value
        print(f"\n{k_level}:")
        print(f"  Violation Rate@{k_val}: {k_metrics[f'violation_rate@{k_val}']:.3f}")
        print(f"  Compliant Rate@{k_val}: {k_metrics[f'compliant_rate@{k_val}']:.3f}")
        print(f"  UNCLEAR Rate@{k_val}: {k_metrics[f'unclear_rate@{k_val}']:.3f}")
        print(f"  ({k_metrics['total_search_terms']} search terms)")
        
        # Show top/bottom search terms by violation rate
        term_details = k_metrics['search_term_details']
        sorted_terms = sorted(term_details.items(), key=lambda x: x[1][f'violation_rate@{k_val}'], reverse=True)
        
        print(f"\n{k_level} - TOP 5 HIGHEST VIOLATION SEARCH TERMS:")
        for i, (term, details) in enumerate(sorted_terms[:5]):
            print(f"  {i+1}. '{term}': {details[f'violation_rate@{k_val}']:.3f} "
                  f"({details['violation_count']}/{details['total_results']})")
        
        print(f"\n{k_level} - TOP 5 LOWEST VIOLATION SEARCH TERMS:")
        for i, (term, details) in enumerate(sorted_terms[-5:]):
            print(f"  {i+1}. '{term}': {details[f'violation_rate@{k_val}']:.3f} "
                  f"({details['violation_count']}/{details['total_results']})")
else:
    print("No L2 metrics available")

=== L2 METRICS (End-to-End) ===

K4:
  Violation Rate@4: 0.275
  Compliant Rate@4: 0.665
  UNCLEAR Rate@4: 0.060
  (795 search terms)

K4 - TOP 5 HIGHEST VIOLATION SEARCH TERMS:
  1. 'beneful grain free': 1.000 (4/4)
  2. 'best no pull harness': 1.000 (4/4)
  3. 'blue buffalo chicken free': 1.000 (4/4)
  4. 'cat collar no bell': 1.000 (4/4)
  5. 'cat food no chicken': 1.000 (4/4)

K4 - TOP 5 LOWEST VIOLATION SEARCH TERMS:
  1. 'wheat free dog food': 0.000 (0/4)
  2. 'wheat free dog treats': 0.000 (0/4)
  3. 'wheat free puppy food': 0.000 (0/4)
  4. 'wholesomes grain free dog food': 0.000 (0/4)
  5. 'wild bird seed no waste': 0.000 (0/4)

K10:
  Violation Rate@10: 0.278
  Compliant Rate@10: 0.650
  UNCLEAR Rate@10: 0.072
  (795 search terms)

K10 - TOP 5 HIGHEST VIOLATION SEARCH TERMS:
  1. 'blue buffalo chicken free': 1.000 (10/10)
  2. 'cat collar no bell': 1.000 (10/10)
  3. 'cat litter no scent': 1.000 (10/10)
  4. 'cat toys no catnip': 1.000 (10/10)
  5. 'cat toys without catnip': 1.000 (4/4)

K10 - TOP 5 LOWEST VIOLATION SEARCH TERMS:
  1. 'wheat free cat food': 0.000 (0/10)
  2. 'wheat free dog food': 0.000 (0/10)
  3. 'wheat free dog treats': 0.000 (0/10)
  4. 'wheat free puppy food': 0.000 (0/10)
  5. 'wild bird seed no waste': 0.000 (0/10)

K36:
  Violation Rate@36: 0.283
  Compliant Rate@36: 0.607
  UNCLEAR Rate@36: 0.110
  (795 search terms)

K36 - TOP 5 HIGHEST VIOLATION SEARCH TERMS:
  1. 'cat toys no catnip': 1.000 (36/36)
  2. 'cat toys without catnip': 1.000 (4/4)
  3. 'chicken free wet cat food': 1.000 (36/36)
  4. 'licks pill free': 1.000 (36/36)
  5. 'low fat grain free dog food': 1.000 (36/36)

K36 - TOP 5 LOWEST VIOLATION SEARCH TERMS:
  1. 'stuffing-free': 0.000 (0/36)
  2. 'wet dog food grain free': 0.000 (0/36)
  3. 'wheat free cat food': 0.000 (0/36)
  4. 'wheat free dog food': 0.000 (0/36)
  5. 'wild bird seed no waste': 0.000 (0/36)

## Breakdown Analysis by Negative Intent

In [13]:
def analyze_by_negative_intent(df, metrics_dict, k=DEFAULT_K):
    """Analyze metrics breakdown by negative intent - using pre-calculated search term metrics
    
    Args:
        df: Original dataframe for intent mapping
        metrics_dict: Dictionary with search_term_details (works with L1 endpoint metrics or L2 metrics)
        k: K value to analyze
    
    Returns:
        Dictionary mapping intent -> {aggregated metrics, search_term_details}
    """
    
    if len(df) == 0 or not metrics_dict:
        return {}
    
    # Get the search term details for this K value
    k_level = f'K{k}'
    if k_level not in metrics_dict:
        print(f"Warning: K{k} not found in metrics")
        return {}
    
    search_term_details = metrics_dict[k_level].get('search_term_details', {})
    
    # Map search terms to their negative intent
    df_top_k = df[df['rank'] <= k].copy()
    search_term_to_intent = df_top_k.drop_duplicates('search_term')[['search_term', 'negative_intent']].set_index('search_term')['negative_intent'].to_dict()
    
    intent_breakdown = {}
    
    # Group search term metrics by negative intent
    for search_term, metrics in search_term_details.items():
        intent = search_term_to_intent.get(search_term)
        if not intent or pd.isna(intent):
            continue
        
        if intent not in intent_breakdown:
            intent_breakdown[intent] = {
                'search_term_details': []
            }
        
        # Add search term with its metrics
        intent_breakdown[intent]['search_term_details'].append({
            'search_term': search_term,
            'violation_rate': metrics.get(f'violation_rate@{k}', 0),
            'compliant_rate': metrics.get(f'compliant_rate@{k}', 0),
            'unclear_rate': metrics.get(f'unclear_rate@{k}', 0),
            'total_results': metrics.get('total_results', 0),
            'violation_count': metrics.get('violation_count', 0),
            'compliant_count': metrics.get('compliant_count', 0),
            'unclear_count': metrics.get('unclear_count', 0)
        })
    
    # Calculate aggregated metrics for each intent
    for intent, data in intent_breakdown.items():
        search_terms = data['search_term_details']
        
        if search_terms:
            agg_violation_rate = sum(m['violation_rate'] for m in search_terms) / len(search_terms)
            agg_compliant_rate = sum(m['compliant_rate'] for m in search_terms) / len(search_terms)
            agg_unclear_rate = sum(m['unclear_rate'] for m in search_terms) / len(search_terms)
        else:
            agg_violation_rate = agg_compliant_rate = agg_unclear_rate = None
        
        data['aggregated'] = {
            'violation_rate': agg_violation_rate,
            'compliant_rate': agg_compliant_rate,
            'unclear_rate': agg_unclear_rate,
            'total_search_terms': len(search_terms)
        }
    
    return intent_breakdown

# Analyze by negative intent for L1 endpoints
all_endpoint_intent_breakdowns = {}
if len(df_final) > 0 and len(l1_metrics) > 0:
    for endpoint, endpoint_metrics in l1_metrics.items():
        endpoint_breakdown = analyze_by_negative_intent(df_final, endpoint_metrics)
        if endpoint_breakdown:
            all_endpoint_intent_breakdowns[endpoint] = endpoint_breakdown
            
            # Display L1 breakdown (skip l2 here, show separately below)
            if endpoint != 'l2':
                print(f"\n=== BREAKDOWN BY NEGATIVE INTENT - {endpoint.upper()} ENDPOINT (K={DEFAULT_K}) ===")
                for intent, metrics in endpoint_breakdown.items():
                    print(f"\n  --- {intent.upper()} ---")
                    agg = metrics['aggregated']
                    print(f"    Violation Rate: {agg['violation_rate']:.3f}, Compliant Rate: {agg['compliant_rate']:.3f}, UNCLEAR Rate: {agg['unclear_rate']:.3f}")
                    print(f"    ({agg['total_search_terms']} search terms)")
                    
                    # Show top 3 search terms by violation rate
                    search_terms = sorted(metrics['search_term_details'], key=lambda x: x['violation_rate'], reverse=True)
                    if search_terms:
                        print(f"    Top search terms:")
                        for i, st_metric in enumerate(search_terms[:3]):
                            print(f"      {i+1}. '{st_metric['search_term']}': {st_metric['violation_rate']:.3f} "
                                  f"({st_metric['violation_count']}/{st_metric['total_results']})")

=== BREAKDOWN BY NEGATIVE INTENT - L1_HYBRID ENDPOINT (K=36) ===

  --- PULL ---
    Violation Rate: 0.388, Compliant Rate: 0.588, UNCLEAR Rate: 0.024
    (53 search terms)
    Top search terms:
      1. 'dog harness medium no pull': 0.917 (33/36)
      2. 'sporn mesh no pull dog harness': 0.913 (21/23)
      3. 'freedom no pull harness': 0.889 (32/36)

  --- GRAIN ---
    Violation Rate: 0.194, Compliant Rate: 0.755, UNCLEAR Rate: 0.051
    (332 search terms)
    Top search terms:
      1. 'hills science diet grain free': 0.944 (34/36)
      2. 'hills science grain free': 0.917 (33/36)
      3. 'science diet grain free': 0.833 (30/36)

  --- ALLER ---
    Violation Rate: 0.306, Compliant Rate: 0.611, UNCLEAR Rate: 0.083
    (1 search terms)
    Top search terms:
      1. 'aller free': 0.306 (11/36)

  --- ALLERGY ---
    Violation Rate: 0.241, Compliant Rate: 0.704, UNCLEAR Rate: 0.056
    (3 search terms)
    Top search terms:
      1. 'allergy free dog treats': 0.306 (11/36)
      2. 'allergy free cat food': 0.250 (9/36)
      3. 'allergy free dog food': 0.167 (6/36)

  --- WASTE FREE ---
    Violation Rate: 0.250, Compliant Rate: 0.750, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'audubon park waste free': 0.250 (9/36)

  --- SHOCK ---
    Violation Rate: 0.661, Compliant Rate: 0.128, UNCLEAR Rate: 0.211
    (5 search terms)
    Top search terms:
      1. 'no shock dog collar': 0.833 (30/36)
      2. 'no shock collar': 0.778 (28/36)
      3. 'no shock training collar': 0.639 (23/36)

  --- ODOR ---
    Violation Rate: 0.119, Compliant Rate: 0.794, UNCLEAR Rate: 0.086
    (10 search terms)
    Top search terms:
      1. 'barkworthies odor free bully sticks': 0.444 (16/36)
      2. 'natural farm odor-free bully sticks': 0.167 (6/36)
      3. 'bully stick odor free': 0.111 (4/36)

  --- MESS ---
    Violation Rate: 0.044, Compliant Rate: 0.573, UNCLEAR Rate: 0.383
    (14 search terms)
    Top search terms:
      1. 'bird seed wild no mess': 0.111 (4/36)
      2. 'kaytee no mess blend wild bird food': 0.111 (4/36)
      3. 'bird food wild no mess': 0.083 (3/36)

  --- WASTE ---
    Violation Rate: 0.068, Compliant Rate: 0.685, UNCLEAR Rate: 0.247
    (9 search terms)
    Top search terms:
      1. 'waste free wild bird seed': 0.194 (7/36)
      2. 'bird seed wild no waste': 0.111 (4/36)
      3. 'waste free bird seed': 0.111 (4/36)

  --- MELT ---
    Violation Rate: 0.035, Compliant Rate: 0.257, UNCLEAR Rate: 0.708
    (4 search terms)
    Top search terms:
      1. 'bird suet cakes no melt': 0.111 (4/36)
      2. 'suet cakes for wild birds no melt': 0.028 (1/36)
      3. 'no melt suet cakes for birds': 0.000 (0/36)

  --- CHICKEN ---
    Violation Rate: 0.688, Compliant Rate: 0.180, UNCLEAR Rate: 0.132
    (59 search terms)
    Top search terms:
      1. 'chicken free wet cat food': 1.000 (36/36)
      2. 'no chicken puppy food': 1.000 (36/36)
      3. 'puppy food no chicken': 1.000 (36/36)

  --- BPA ---
    Violation Rate: 0.000, Compliant Rate: 0.000, UNCLEAR Rate: 1.000
    (1 search terms)
    Top search terms:
      1. 'bpa free litter box': 0.000 (0/36)

  --- D3 ---
    Violation Rate: 0.361, Compliant Rate: 0.222, UNCLEAR Rate: 0.417
    (1 search terms)
    Top search terms:
      1. 'calcium without d3': 0.361 (13/36)

  --- HIDE ---
    Violation Rate: 0.238, Compliant Rate: 0.755, UNCLEAR Rate: 0.007
    (36 search terms)
    Top search terms:
      1. 'hide free': 0.944 (34/36)
      2. 'hide free dog chews': 0.833 (30/36)
      3. 'hide free chews': 0.778 (28/36)

  --- BELL ---
    Violation Rate: 0.972, Compliant Rate: 0.000, UNCLEAR Rate: 0.028
    (1 search terms)
    Top search terms:
      1. 'cat collar no bell': 0.972 (35/36)

  --- PRESCRIPTION ---
    Violation Rate: 0.306, Compliant Rate: 0.514, UNCLEAR Rate: 0.181
    (2 search terms)
    Top search terms:
      1. 'cat dewormer no prescription': 0.417 (15/36)
      2. 'non prescription pain meds for dogs': 0.194 (7/36)

  --- ADDITIVES ---
    Violation Rate: 0.194, Compliant Rate: 0.000, UNCLEAR Rate: 0.806
    (1 search terms)
    Top search terms:
      1. 'cat food with no additives': 0.194 (7/36)

  --- DUST ---
    Violation Rate: 0.060, Compliant Rate: 0.220, UNCLEAR Rate: 0.720
    (14 search terms)
    Top search terms:
      1. 'clumping cat litter dust free': 0.194 (7/36)
      2. 'dust free clumping litter': 0.139 (5/36)
      3. 'cat litter no dust': 0.083 (3/36)

  --- FRAGRANCE ---
    Violation Rate: 0.231, Compliant Rate: 0.565, UNCLEAR Rate: 0.204
    (3 search terms)
    Top search terms:
      1. 'fragrance free dog shampoo': 0.306 (11/36)
      2. 'cat litter fragrance free': 0.222 (8/36)
      3. 'fragrance free cat litter': 0.167 (6/36)

  --- SCENT ---
    Violation Rate: 0.796, Compliant Rate: 0.120, UNCLEAR Rate: 0.083
    (3 search terms)
    Top search terms:
      1. 'cat litter no scent': 0.944 (34/36)
      2. 'scent free cat litter': 0.778 (28/36)
      3. 'scent free litter': 0.667 (24/36)

  --- TRACKING ---
    Violation Rate: 0.256, Compliant Rate: 0.356, UNCLEAR Rate: 0.389
    (5 search terms)
    Top search terms:
      1. 'no tracking cat litter': 0.333 (12/36)
      2. 'no tracking litter': 0.333 (12/36)
      3. 'cat litter no tracking': 0.278 (10/36)

  --- PEE ---
    Violation Rate: 0.833, Compliant Rate: 0.167, UNCLEAR Rate: 0.000
    (2 search terms)
    Top search terms:
      1. 'no pee': 0.944 (34/36)
      2. 'cat no pee': 0.722 (26/36)

  --- SCRATCH ---
    Violation Rate: 0.701, Compliant Rate: 0.285, UNCLEAR Rate: 0.014
    (4 search terms)
    Top search terms:
      1. 'no scratch': 1.000 (36/36)
      2. 'cat no scratch': 0.944 (34/36)
      3. 'no scratch spray': 0.472 (17/36)

  --- CATNIP ---
    Violation Rate: 1.000, Compliant Rate: 0.000, UNCLEAR Rate: 0.000
    (2 search terms)
    Top search terms:
      1. 'cat toys no catnip': 1.000 (36/36)
      2. 'cat toys without catnip': 1.000 (4/4)

  --- CARPET ---
    Violation Rate: 0.583, Compliant Rate: 0.028, UNCLEAR Rate: 0.389
    (1 search terms)
    Top search terms:
      1. 'cat tree no carpet': 0.583 (21/36)

  --- RAWHIDE ---
    Violation Rate: 0.273, Compliant Rate: 0.685, UNCLEAR Rate: 0.042
    (47 search terms)
    Top search terms:
      1. 'dog bones no rawhide': 0.861 (31/36)
      2. 'no hide rawhide': 0.833 (30/36)
      3. 'no rawhide bones': 0.806 (29/36)

  --- POO ---
    Violation Rate: 0.528, Compliant Rate: 0.472, UNCLEAR Rate: 0.000
    (4 search terms)
    Top search terms:
      1. 'chew no poo': 0.722 (26/36)
      2. 'no poo': 0.583 (21/36)
      3. 'no poo chews for dogs': 0.528 (19/36)

  --- POOP ---
    Violation Rate: 0.632, Compliant Rate: 0.368, UNCLEAR Rate: 0.000
    (4 search terms)
    Top search terms:
      1. 'chew no poop': 0.722 (26/36)
      2. 'no poop': 0.722 (26/36)
      3. 'no eat poop': 0.639 (23/36)

  --- MEDICATED ---
    Violation Rate: 0.278, Compliant Rate: 0.528, UNCLEAR Rate: 0.194
    (1 search terms)
    Top search terms:
      1. 'chick starter feed non medicated': 0.278 (10/36)

  --- NON GMO ---
    Violation Rate: 0.769, Compliant Rate: 0.093, UNCLEAR Rate: 0.139
    (3 search terms)
    Top search terms:
      1. 'chicken feed non gmo': 0.972 (35/36)
      2. 'non gmo dog treats': 0.694 (25/36)
      3. 'organic non gmo chicken feed': 0.639 (23/36)

  --- SOY ---
    Violation Rate: 0.046, Compliant Rate: 0.532, UNCLEAR Rate: 0.421
    (6 search terms)
    Top search terms:
      1. 'soy free horse feed': 0.111 (4/36)
      2. 'soy free layer feed': 0.111 (4/36)
      3. 'organic soy free chicken feed': 0.028 (1/36)

  --- CHOKE ---
    Violation Rate: 0.056, Compliant Rate: 0.944, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'choke free harness': 0.056 (2/36)

  --- SUNFLOWER SEEDS ---
    Violation Rate: 0.444, Compliant Rate: 0.028, UNCLEAR Rate: 0.528
    (1 search terms)
    Top search terms:
      1. 'cockatiel food no sunflower seeds': 0.444 (16/36)

  --- CORN AND SOY ---
    Violation Rate: 0.139, Compliant Rate: 0.528, UNCLEAR Rate: 0.333
    (1 search terms)
    Top search terms:
      1. 'corn and soy free chicken feed': 0.139 (5/36)

  --- CORN ---
    Violation Rate: 0.151, Compliant Rate: 0.525, UNCLEAR Rate: 0.324
    (9 search terms)
    Top search terms:
      1. 'pigeon feed no corn': 0.389 (14/36)
      2. 'pigeon food no corn': 0.389 (14/36)
      3. 'corn free chicken scratch': 0.306 (11/36)

  --- FREE ---
    Violation Rate: 0.148, Compliant Rate: 0.852, UNCLEAR Rate: 0.000
    (2 search terms)
    Top search terms:
      1. 'cough free horse': 0.167 (6/36)
      2. 'tidy cats free': 0.129 (4/31)

  --- SEAFOOD ---
    Violation Rate: 0.500, Compliant Rate: 0.389, UNCLEAR Rate: 0.111
    (1 search terms)
    Top search terms:
      1. 'delectables non seafood': 0.500 (18/36)

  --- POULTRY ---
    Violation Rate: 0.643, Compliant Rate: 0.175, UNCLEAR Rate: 0.183
    (7 search terms)
    Top search terms:
      1. 'poultry free wet dog food': 0.806 (29/36)
      2. 'poultry free cat food': 0.750 (27/36)
      3. 'poultry free': 0.667 (24/36)

  --- ESCAPE ---
    Violation Rate: 0.111, Compliant Rate: 0.833, UNCLEAR Rate: 0.056
    (1 search terms)
    Top search terms:
      1. 'dog harness no escape': 0.111 (4/36)

  --- ZIP ---
    Violation Rate: 0.046, Compliant Rate: 0.398, UNCLEAR Rate: 0.556
    (3 search terms)
    Top search terms:
      1. 'small black stroller no zip': 0.083 (3/36)
      2. 'no zip stroller': 0.056 (2/36)
      3. 'dog stroller no zip': 0.000 (0/36)

  --- SQUEAK ---
    Violation Rate: 0.743, Compliant Rate: 0.188, UNCLEAR Rate: 0.069
    (4 search terms)
    Top search terms:
      1. 'dog toy no squeak': 0.833 (30/36)
      2. 'dog toys no squeak': 0.806 (29/36)
      3. 'no squeak dog toys': 0.694 (25/36)

  --- SQUEAKER ---
    Violation Rate: 0.944, Compliant Rate: 0.028, UNCLEAR Rate: 0.028
    (1 search terms)
    Top search terms:
      1. 'dog toy no squeaker': 0.944 (34/36)

  --- STUFFING ---
    Violation Rate: 0.029, Compliant Rate: 0.937, UNCLEAR Rate: 0.034
    (24 search terms)
    Top search terms:
      1. 'dog toys for large dogs no stuffing': 0.167 (6/36)
      2. 'stuffing free dog toys small': 0.083 (3/36)
      3. 'dog toys with no stuffing': 0.056 (2/36)

  --- TEETH ---
    Violation Rate: 0.722, Compliant Rate: 0.250, UNCLEAR Rate: 0.028
    (2 search terms)
    Top search terms:
      1. 'treats for dogs with no teeth': 0.750 (27/36)
      2. 'dog treats for dogs with no teeth': 0.694 (25/36)

  --- SPILL ---
    Violation Rate: 0.287, Compliant Rate: 0.634, UNCLEAR Rate: 0.079
    (6 search terms)
    Top search terms:
      1. 'no spill dog bowl': 0.361 (13/36)
      2. 'python no spill': 0.333 (12/36)
      3. 'water bowl no spill': 0.333 (12/36)

  --- FAT ---
    Violation Rate: 0.236, Compliant Rate: 0.306, UNCLEAR Rate: 0.458
    (2 search terms)
    Top search terms:
      1. 'fat free dog treats': 0.389 (14/36)
      2. 'no fat dog treats': 0.083 (3/36)

  --- FISH ---
    Violation Rate: 0.889, Compliant Rate: 0.056, UNCLEAR Rate: 0.056
    (1 search terms)
    Top search terms:
      1. 'fish free cat food': 0.889 (32/36)

  --- EARS ---
    Violation Rate: 0.708, Compliant Rate: 0.194, UNCLEAR Rate: 0.097
    (2 search terms)
    Top search terms:
      1. 'fly mask without ears': 0.750 (27/36)
      2. 'horse fly mask without ears': 0.667 (24/36)

  --- NON CLUMPING ---
    Violation Rate: 0.639, Compliant Rate: 0.341, UNCLEAR Rate: 0.020
    (7 search terms)
    Top search terms:
      1. 'non clumping cat litter': 0.861 (31/36)
      2. 'non clumping kitty litter': 0.833 (30/36)
      3. 'litter non clumping': 0.722 (26/36)

  --- GAIN ---
    Violation Rate: 0.083, Compliant Rate: 0.917, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'gain free dog food': 0.083 (3/36)

  --- GLUTEN ---
    Violation Rate: 0.133, Compliant Rate: 0.650, UNCLEAR Rate: 0.217
    (10 search terms)
    Top search terms:
      1. 'victor hi-pro plus 30/20 active sporting high protein gluten-free dry dog food': 0.333 (12/36)
      2. 'gluten free puppy food': 0.306 (11/36)
      3. 'gluten free dry dog food': 0.250 (9/36)

  --- GMO ---
    Violation Rate: 0.012, Compliant Rate: 0.845, UNCLEAR Rate: 0.143
    (7 search terms)
    Top search terms:
      1. 'non gmo wet dog food': 0.083 (3/36)
      2. 'gmo free dog food': 0.000 (0/36)
      3. 'non gmo': 0.000 (0/36)

  --- GRAIN, CHICKEN ---
    Violation Rate: 0.535, Compliant Rate: 0.451, UNCLEAR Rate: 0.014
    (4 search terms)
    Top search terms:
      1. 'grain free chicken free dog treats': 0.750 (27/36)
      2. 'grain free chicken free dog food': 0.722 (26/36)
      3. 'grain and chicken free dog food': 0.667 (24/36)

  --- PROBIOTIC ---
    Violation Rate: 0.000, Compliant Rate: 0.000, UNCLEAR Rate: 1.000
    (1 search terms)
    Top search terms:
      1. 'grain free dogfood no probiotic': 0.000 (0/36)

  --- IODINE ---
    Violation Rate: 0.000, Compliant Rate: 0.056, UNCLEAR Rate: 0.944
    (1 search terms)
    Top search terms:
      1. 'iodine free cat food': 0.000 (0/36)

  --- CLUMPING ---
    Violation Rate: 0.097, Compliant Rate: 0.903, UNCLEAR Rate: 0.000
    (2 search terms)
    Top search terms:
      1. 'non clumping': 0.111 (4/36)
      2. 'kitty litter non clumping': 0.083 (3/36)

  --- LEGUME ---
    Violation Rate: 0.472, Compliant Rate: 0.083, UNCLEAR Rate: 0.444
    (1 search terms)
    Top search terms:
      1. 'legume free dog food': 0.472 (17/36)

  --- PILL ---
    Violation Rate: 1.000, Compliant Rate: 0.000, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'licks pill free': 1.000 (36/36)

  --- GRAIN, FAT ---
    Violation Rate: 1.000, Compliant Rate: 0.000, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'low fat grain free dog food': 1.000 (36/36)

  --- BARK ---
    Violation Rate: 0.889, Compliant Rate: 0.111, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'no bark': 0.889 (32/36)

  --- NO BARK ---
    Violation Rate: 1.000, Compliant Rate: 0.000, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'no bark collars': 1.000 (36/36)

  --- CAT PEE ---
    Violation Rate: 0.333, Compliant Rate: 0.667, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'no cat pee': 0.333 (12/36)

  --- CHEW ---
    Violation Rate: 0.300, Compliant Rate: 0.678, UNCLEAR Rate: 0.022
    (5 search terms)
    Top search terms:
      1. 'no chew': 0.861 (31/36)
      2. 'no chew spray for cats': 0.278 (10/36)
      3. 'no chew dog bed': 0.139 (5/36)

  --- CLUMP ---
    Violation Rate: 0.778, Compliant Rate: 0.222, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'no clump litter': 0.778 (28/36)

  --- GROW ---
    Violation Rate: 0.028, Compliant Rate: 0.306, UNCLEAR Rate: 0.667
    (1 search terms)
    Top search terms:
      1. 'no grow bird seed': 0.028 (1/36)

  --- HIDES ---
    Violation Rate: 0.111, Compliant Rate: 0.861, UNCLEAR Rate: 0.028
    (1 search terms)
    Top search terms:
      1. 'no hides': 0.111 (4/36)

  --- HOLES ---
    Violation Rate: 0.226, Compliant Rate: 0.742, UNCLEAR Rate: 0.032
    (1 search terms)
    Top search terms:
      1. 'no holes': 0.226 (7/31)

  --- LICK ---
    Violation Rate: 0.917, Compliant Rate: 0.083, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'no lick': 0.917 (33/36)

  --- NO MELT ---
    Violation Rate: 0.500, Compliant Rate: 0.222, UNCLEAR Rate: 0.278
    (1 search terms)
    Top search terms:
      1. 'no melt suet': 0.500 (18/36)

  --- MILLET ---
    Violation Rate: 0.389, Compliant Rate: 0.056, UNCLEAR Rate: 0.556
    (1 search terms)
    Top search terms:
      1. 'no millet bird seed': 0.389 (14/36)

  --- POOP EATING ---
    Violation Rate: 0.361, Compliant Rate: 0.583, UNCLEAR Rate: 0.056
    (1 search terms)
    Top search terms:
      1. 'no poop eating': 0.361 (13/36)

  --- SCOOT ---
    Violation Rate: 0.556, Compliant Rate: 0.417, UNCLEAR Rate: 0.028
    (1 search terms)
    Top search terms:
      1. 'no scoot for dogs': 0.556 (20/36)

  --- SPRAY ---
    Violation Rate: 1.000, Compliant Rate: 0.000, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'no spray cat': 1.000 (36/36)

  --- SQUIRREL ---
    Violation Rate: 0.333, Compliant Rate: 0.583, UNCLEAR Rate: 0.083
    (1 search terms)
    Top search terms:
      1. 'no squirrel bird seed': 0.333 (12/36)

  --- SUGAR ---
    Violation Rate: 0.206, Compliant Rate: 0.150, UNCLEAR Rate: 0.644
    (5 search terms)
    Top search terms:
      1. 'sugar free': 0.389 (14/36)
      2. 'sugar free horse treats': 0.306 (11/36)
      3. 'no sugar horse treats': 0.222 (8/36)

  --- TIP ---
    Violation Rate: 0.000, Compliant Rate: 0.875, UNCLEAR Rate: 0.125
    (2 search terms)
    Top search terms:
      1. 'no tip water bowl': 0.000 (0/36)
      2. 'non tip water bowl': 0.000 (0/36)

  --- TOOT ---
    Violation Rate: 0.226, Compliant Rate: 0.710, UNCLEAR Rate: 0.065
    (1 search terms)
    Top search terms:
      1. 'no toot': 0.226 (7/31)

  --- TRACK ---
    Violation Rate: 0.306, Compliant Rate: 0.194, UNCLEAR Rate: 0.500
    (1 search terms)
    Top search terms:
      1. 'no track cat litter': 0.306 (11/36)

  --- NON ABSORBENT ---
    Violation Rate: 0.528, Compliant Rate: 0.417, UNCLEAR Rate: 0.056
    (1 search terms)
    Top search terms:
      1. 'non absorbent cat litter': 0.528 (19/36)

  --- CLAY ---
    Violation Rate: 0.278, Compliant Rate: 0.694, UNCLEAR Rate: 0.028
    (2 search terms)
    Top search terms:
      1. 'non clay litter': 0.361 (13/36)
      2. 'non clay cat litter': 0.194 (7/36)

  --- NON CLUMPING UNSCENTED CAT LITTER

THE USER IS ACTUALLY LOOKING FOR CAT LITTER ---
    Violation Rate: 0.778, Compliant Rate: 0.194, UNCLEAR Rate: 0.028
    (1 search terms)
    Top search terms:
      1. 'non clumping unscented cat litter': 0.778 (28/36)

  --- KIBBLE ---
    Violation Rate: 1.000, Compliant Rate: 0.000, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'non kibble dog food': 1.000 (36/36)

  --- NON PRESCRIPTION ---
    Violation Rate: 0.292, Compliant Rate: 0.611, UNCLEAR Rate: 0.097
    (2 search terms)
    Top search terms:
      1. 'non prescription flea meds': 0.333 (12/36)
      2. 'non prescription flea medicine': 0.250 (9/36)

  --- SCENTED ---
    Violation Rate: 0.444, Compliant Rate: 0.500, UNCLEAR Rate: 0.056
    (1 search terms)
    Top search terms:
      1. 'non scented litter': 0.444 (16/36)

  --- SQUEAKY ---
    Violation Rate: 0.861, Compliant Rate: 0.000, UNCLEAR Rate: 0.139
    (1 search terms)
    Top search terms:
      1. 'non squeaky dog toys': 0.861 (31/36)

  --- STUFFED ---
    Violation Rate: 0.222, Compliant Rate: 0.750, UNCLEAR Rate: 0.028
    (1 search terms)
    Top search terms:
      1. 'non stuffed dog toys': 0.222 (8/36)

  --- TOXIC ---
    Violation Rate: 0.000, Compliant Rate: 1.000, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'non toxic cat litter': 0.000 (0/36)

  --- PEA ---
    Violation Rate: 0.361, Compliant Rate: 0.056, UNCLEAR Rate: 0.583
    (1 search terms)
    Top search terms:
      1. 'pea free dog food': 0.361 (13/36)

  --- PROTEIN ---
    Violation Rate: 0.944, Compliant Rate: 0.028, UNCLEAR Rate: 0.028
    (1 search terms)
    Top search terms:
      1. 'protein free dog treats': 0.944 (34/36)

  --- RICE ---
    Violation Rate: 0.111, Compliant Rate: 0.500, UNCLEAR Rate: 0.389
    (1 search terms)
    Top search terms:
      1. 'rice free dog food': 0.111 (4/36)

  --- SALT ---
    Violation Rate: 0.000, Compliant Rate: 0.000, UNCLEAR Rate: 1.000
    (1 search terms)
    Top search terms:
      1. 'salt free dog food': 0.000 (0/36)

  --- SHELL ---

In [14]:
# Analyze by negative intent for L2 (end-to-end)
l2_intent_breakdown = {}
if len(df_final) > 0 and len(l2_metrics) > 0:
    l2_intent_breakdown = analyze_by_negative_intent(df_final, l2_metrics)
    
    print(f"\n=== BREAKDOWN BY NEGATIVE INTENT - L2 (END-TO-END) (K={DEFAULT_K}) ===")
    for intent, metrics in l2_intent_breakdown.items():
        print(f"\n  --- {intent.upper()} ---")
        agg = metrics['aggregated']
        print(f"    Violation Rate: {agg['violation_rate']:.3f}, Compliant Rate: {agg['compliant_rate']:.3f}, UNCLEAR Rate: {agg['unclear_rate']:.3f}")
        print(f"    ({agg['total_search_terms']} search terms)")
        
        # Show top 5 search terms by violation rate
        search_terms = sorted(metrics['search_term_details'], key=lambda x: x['violation_rate'], reverse=True)
        if search_terms:
            print(f"    Top search terms:")
            for i, st_metric in enumerate(search_terms[:5]):
                print(f"      {i+1}. '{st_metric['search_term']}': {st_metric['violation_rate']:.3f} "
                      f"({st_metric['violation_count']}/{st_metric['total_results']})")

=== BREAKDOWN BY NEGATIVE INTENT - L2 (END-TO-END) (K=36) ===

  --- PULL ---
    Violation Rate: 0.386, Compliant Rate: 0.589, UNCLEAR Rate: 0.024
    (53 search terms)
    Top search terms:
      1. 'sporn mesh no pull dog harness': 0.913 (21/23)
      2. 'dog harness medium no pull': 0.889 (32/36)
      3. 'freedom no pull harness': 0.889 (32/36)
      4. 'adjustable no pull harness': 0.861 (31/36)
      5. 'no slip harness': 0.861 (31/36)

  --- GRAIN ---
    Violation Rate: 0.192, Compliant Rate: 0.757, UNCLEAR Rate: 0.051
    (332 search terms)
    Top search terms:
      1. 'hills science diet grain free': 0.944 (34/36)
      2. 'hills science grain free': 0.917 (33/36)
      3. 'science diet grain free': 0.833 (30/36)
      4. 'purina pro plan grain free': 0.778 (28/36)
      5. 'purina one grain free dog food': 0.750 (27/36)

  --- ALLER ---
    Violation Rate: 0.306, Compliant Rate: 0.611, UNCLEAR Rate: 0.083
    (1 search terms)
    Top search terms:
      1. 'aller free': 0.306 (11/36)

  --- ALLERGY ---
    Violation Rate: 0.241, Compliant Rate: 0.704, UNCLEAR Rate: 0.056
    (3 search terms)
    Top search terms:
      1. 'allergy free dog treats': 0.306 (11/36)
      2. 'allergy free cat food': 0.250 (9/36)
      3. 'allergy free dog food': 0.167 (6/36)

  --- WASTE FREE ---
    Violation Rate: 0.278, Compliant Rate: 0.722, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'audubon park waste free': 0.278 (10/36)

  --- SHOCK ---
    Violation Rate: 0.656, Compliant Rate: 0.133, UNCLEAR Rate: 0.211
    (5 search terms)
    Top search terms:
      1. 'no shock dog collar': 0.833 (30/36)
      2. 'no shock collar': 0.750 (27/36)
      3. 'no shock training collar': 0.667 (24/36)
      4. 'no shock bark collar': 0.528 (19/36)
      5. 'bark collar no shock': 0.500 (18/36)

  --- ODOR ---
    Violation Rate: 0.117, Compliant Rate: 0.797, UNCLEAR Rate: 0.086
    (10 search terms)
    Top search terms:
      1. 'barkworthies odor free bully sticks': 0.444 (16/36)
      2. 'natural farm odor-free bully sticks': 0.167 (6/36)
      3. 'bully stick odor free': 0.111 (4/36)
      4. 'odor free bully stick': 0.111 (4/36)
      5. 'odor free bully sticks': 0.083 (3/36)

  --- MESS ---
    Violation Rate: 0.050, Compliant Rate: 0.571, UNCLEAR Rate: 0.379
    (14 search terms)
    Top search terms:
      1. 'bird seed wild no mess': 0.111 (4/36)
      2. 'kaytee no mess blend wild bird food': 0.111 (4/36)
      3. 'bird food wild no mess': 0.083 (3/36)
      4. 'kaytee wild bird food no mess': 0.083 (3/36)
      5. 'mess free bird seed': 0.083 (3/36)

  --- WASTE ---
    Violation Rate: 0.071, Compliant Rate: 0.676, UNCLEAR Rate: 0.253
    (9 search terms)
    Top search terms:
      1. 'waste free wild bird seed': 0.222 (8/36)
      2. 'bird seed wild no waste': 0.111 (4/36)
      3. 'waste free bird seed': 0.111 (4/36)
      4. 'no waste wild bird food': 0.083 (3/36)
      5. 'no waste wild bird seed': 0.056 (2/36)

  --- MELT ---
    Violation Rate: 0.035, Compliant Rate: 0.264, UNCLEAR Rate: 0.701
    (4 search terms)
    Top search terms:
      1. 'bird suet cakes no melt': 0.111 (4/36)
      2. 'suet cakes for wild birds no melt': 0.028 (1/36)
      3. 'no melt suet cakes for birds': 0.000 (0/36)
      4. 'no melt suet cakes for wild birds': 0.000 (0/36)

  --- CHICKEN ---
    Violation Rate: 0.686, Compliant Rate: 0.184, UNCLEAR Rate: 0.130
    (59 search terms)
    Top search terms:
      1. 'chicken free wet cat food': 1.000 (36/36)
      2. 'no chicken puppy food': 1.000 (36/36)
      3. 'puppy food no chicken': 1.000 (36/36)
      4. 'cat treats no chicken': 0.972 (35/36)
      5. 'puppy food with no chicken': 0.972 (35/36)

  --- BPA ---
    Violation Rate: 0.000, Compliant Rate: 0.000, UNCLEAR Rate: 1.000
    (1 search terms)
    Top search terms:
      1. 'bpa free litter box': 0.000 (0/36)

  --- D3 ---
    Violation Rate: 0.333, Compliant Rate: 0.222, UNCLEAR Rate: 0.444
    (1 search terms)
    Top search terms:
      1. 'calcium without d3': 0.333 (12/36)

  --- HIDE ---
    Violation Rate: 0.239, Compliant Rate: 0.753, UNCLEAR Rate: 0.008
    (36 search terms)
    Top search terms:
      1. 'hide free': 0.944 (34/36)
      2. 'hide free dog chews': 0.833 (30/36)
      3. 'hide free chews': 0.778 (28/36)
      4. 'hide free chicken recipe sticks': 0.583 (21/36)
      5. 'canine naturals hide free': 0.556 (20/36)

  --- BELL ---
    Violation Rate: 0.972, Compliant Rate: 0.000, UNCLEAR Rate: 0.028
    (1 search terms)
    Top search terms:
      1. 'cat collar no bell': 0.972 (35/36)

  --- PRESCRIPTION ---
    Violation Rate: 0.319, Compliant Rate: 0.500, UNCLEAR Rate: 0.181
    (2 search terms)
    Top search terms:
      1. 'cat dewormer no prescription': 0.417 (15/36)
      2. 'non prescription pain meds for dogs': 0.222 (8/36)

  --- ADDITIVES ---
    Violation Rate: 0.194, Compliant Rate: 0.000, UNCLEAR Rate: 0.806
    (1 search terms)
    Top search terms:
      1. 'cat food with no additives': 0.194 (7/36)

  --- DUST ---
    Violation Rate: 0.060, Compliant Rate: 0.216, UNCLEAR Rate: 0.724
    (14 search terms)
    Top search terms:
      1. 'clumping cat litter dust free': 0.194 (7/36)
      2. 'dust free clumping litter': 0.139 (5/36)
      3. 'cat litter no dust': 0.083 (3/36)
      4. 'dust free clumping cat litter': 0.083 (3/36)
      5. 'no dust clumping cat litter': 0.083 (3/36)

  --- FRAGRANCE ---
    Violation Rate: 0.241, Compliant Rate: 0.565, UNCLEAR Rate: 0.194
    (3 search terms)
    Top search terms:
      1. 'fragrance free dog shampoo': 0.333 (12/36)
      2. 'cat litter fragrance free': 0.222 (8/36)
      3. 'fragrance free cat litter': 0.167 (6/36)

  --- SCENT ---
    Violation Rate: 0.796, Compliant Rate: 0.120, UNCLEAR Rate: 0.083
    (3 search terms)
    Top search terms:
      1. 'cat litter no scent': 0.944 (34/36)
      2. 'scent free cat litter': 0.778 (28/36)
      3. 'scent free litter': 0.667 (24/36)

  --- TRACKING ---
    Violation Rate: 0.261, Compliant Rate: 0.350, UNCLEAR Rate: 0.389
    (5 search terms)
    Top search terms:
      1. 'no tracking cat litter': 0.333 (12/36)
      2. 'no tracking litter': 0.333 (12/36)
      3. 'cat litter no tracking': 0.306 (11/36)
      4. 'non tracking litter': 0.194 (7/36)
      5. 'non tracking cat litter': 0.139 (5/36)

  --- PEE ---
    Violation Rate: 0.833, Compliant Rate: 0.167, UNCLEAR Rate: 0.000
    (2 search terms)
    Top search terms:
      1. 'no pee': 0.944 (34/36)
      2. 'cat no pee': 0.722 (26/36)

  --- SCRATCH ---
    Violation Rate: 0.701, Compliant Rate: 0.285, UNCLEAR Rate: 0.014
    (4 search terms)
    Top search terms:
      1. 'no scratch': 1.000 (36/36)
      2. 'cat no scratch': 0.944 (34/36)
      3. 'no scratch spray': 0.472 (17/36)
      4. 'no scratch spray for cats': 0.389 (14/36)

  --- CATNIP ---
    Violation Rate: 1.000, Compliant Rate: 0.000, UNCLEAR Rate: 0.000
    (2 search terms)
    Top search terms:
      1. 'cat toys no catnip': 1.000 (36/36)
      2. 'cat toys without catnip': 1.000 (4/4)

  --- CARPET ---
    Violation Rate: 0.611, Compliant Rate: 0.028, UNCLEAR Rate: 0.361
    (1 search terms)
    Top search terms:
      1. 'cat tree no carpet': 0.611 (22/36)

  --- RAWHIDE ---
    Violation Rate: 0.270, Compliant Rate: 0.689, UNCLEAR Rate: 0.041
    (47 search terms)
    Top search terms:
      1. 'dog bones no rawhide': 0.861 (31/36)
      2. 'no hide rawhide': 0.833 (30/36)
      3. 'no rawhide bones': 0.778 (28/36)
      4. 'non raw hide': 0.694 (25/36)
      5. 'no hide raw hide': 0.583 (21/36)

  --- POO ---
    Violation Rate: 0.507, Compliant Rate: 0.493, UNCLEAR Rate: 0.000
    (4 search terms)
    Top search terms:
      1. 'chew no poo': 0.694 (25/36)
      2. 'no poo': 0.556 (20/36)
      3. 'no poo chews for dogs': 0.528 (19/36)
      4. 'no poo chews': 0.250 (9/36)

  --- POOP ---
    Violation Rate: 0.625, Compliant Rate: 0.375, UNCLEAR Rate: 0.000
    (4 search terms)
    Top search terms:
      1. 'chew no poop': 0.722 (26/36)
      2. 'no poop': 0.722 (26/36)
      3. 'no eat poop': 0.611 (22/36)
      4. 'no poop chews': 0.444 (16/36)

  --- MEDICATED ---
    Violation Rate: 0.278, Compliant Rate: 0.528, UNCLEAR Rate: 0.194
    (1 search terms)
    Top search terms:
      1. 'chick starter feed non medicated': 0.278 (10/36)

  --- NON GMO ---
    Violation Rate: 0.759, Compliant Rate: 0.093, UNCLEAR Rate: 0.148
    (3 search terms)
    Top search terms:
      1. 'chicken feed non gmo': 0.944 (34/36)
      2. 'non gmo dog treats': 0.694 (25/36)
      3. 'organic non gmo chicken feed': 0.639 (23/36)

  --- SOY ---
    Violation Rate: 0.046, Compliant Rate: 0.532, UNCLEAR Rate: 0.421
    (6 search terms)
    Top search terms:
      1. 'soy free horse feed': 0.111 (4/36)
      2. 'soy free layer feed': 0.111 (4/36)
      3. 'organic soy free chicken feed': 0.028 (1/36)
      4. 'soy free chicken feed': 0.028 (1/36)
      5. 'chicken feed soy free': 0.000 (0/36)

  --- CHOKE ---
    Violation Rate: 0.056, Compliant Rate: 0.944, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'choke free harness': 0.056 (2/36)

  --- SUNFLOWER SEEDS ---
    Violation Rate: 0.444, Compliant Rate: 0.028, UNCLEAR Rate: 0.528
    (1 search terms)
    Top search terms:
      1. 'cockatiel food no sunflower seeds': 0.444 (16/36)

  --- CORN AND SOY ---
    Violation Rate: 0.139, Compliant Rate: 0.500, UNCLEAR Rate: 0.361
    (1 search terms)
    Top search terms:
      1. 'corn and soy free chicken feed': 0.139 (5/36)

  --- CORN ---
    Violation Rate: 0.157, Compliant Rate: 0.519, UNCLEAR Rate: 0.324
    (9 search terms)
    Top search terms:
      1. 'pigeon feed no corn': 0.444 (16/36)
      2. 'pigeon food no corn': 0.389 (14/36)
      3. 'corn free chicken scratch': 0.306 (11/36)
      4. 'corn free chicken feed': 0.167 (6/36)
      5. 'dog food no corn': 0.056 (2/36)

  --- FREE ---
    Violation Rate: 0.148, Compliant Rate: 0.852, UNCLEAR Rate: 0.000
    (2 search terms)
    Top search terms:
      1. 'cough free horse': 0.167 (6/36)
      2. 'tidy cats free': 0.129 (4/31)

  --- SEAFOOD ---
    Violation Rate: 0.500, Compliant Rate: 0.389, UNCLEAR Rate: 0.111
    (1 search terms)
    Top search terms:
      1. 'delectables non seafood': 0.500 (18/36)

  --- POULTRY ---
    Violation Rate: 0.635, Compliant Rate: 0.167, UNCLEAR Rate: 0.198
    (7 search terms)
    Top search terms:
      1. 'poultry free wet dog food': 0.778 (28/36)
      2. 'poultry free cat food': 0.722 (26/36)
      3. 'poultry free dog treats': 0.667 (24/36)
      4. 'poultry free': 0.639 (23/36)
      5. 'no poultry dog food': 0.611 (22/36)

  --- ESCAPE ---
    Violation Rate: 0.111, Compliant Rate: 0.833, UNCLEAR Rate: 0.056
    (1 search terms)
    Top search terms:
      1. 'dog harness no escape': 0.111 (4/36)

  --- ZIP ---
    Violation Rate: 0.046, Compliant Rate: 0.398, UNCLEAR Rate: 0.556
    (3 search terms)
    Top search terms:
      1. 'small black stroller no zip': 0.083 (3/36)
      2. 'no zip stroller': 0.056 (2/36)
      3. 'dog stroller no zip': 0.000 (0/36)

  --- SQUEAK ---
    Violation Rate: 0.750, Compliant Rate: 0.188, UNCLEAR Rate: 0.062
    (4 search terms)
    Top search terms:
      1. 'dog toy no squeak': 0.861 (31/36)
      2. 'dog toys no squeak': 0.806 (29/36)
      3. 'no squeak dog toys': 0.694 (25/36)
      4. 'no squeak dog toy': 0.639 (23/36)

  --- SQUEAKER ---
    Violation Rate: 0.944, Compliant Rate: 0.028, UNCLEAR Rate: 0.028
    (1 search terms)
    Top search terms:
      1. 'dog toy no squeaker': 0.944 (34/36)

  --- STUFFING ---
    Violation Rate: 0.029, Compliant Rate: 0.937, UNCLEAR Rate: 0.034
    (24 search terms)
    Top search terms:
      1. 'dog toys for large dogs no stuffing': 0.167 (6/36)
      2. 'stuffing free dog toys small': 0.083 (3/36)
      3. 'dog toys with no stuffing': 0.056 (2/36)
      4. 'no stuffing': 0.056 (2/36)
      5. 'no stuffing dog toy': 0.056 (2/36)

  --- TEETH ---
    Violation Rate: 0.722, Compliant Rate: 0.250, UNCLEAR Rate: 0.028
    (2 search terms)
    Top search terms:
      1. 'treats for dogs with no teeth': 0.750 (27/36)
      2. 'dog treats for dogs with no teeth': 0.694 (25/36)

  --- SPILL ---
    Violation Rate: 0.282, Compliant Rate: 0.644, UNCLEAR Rate: 0.074
    (6 search terms)
    Top search terms:
      1. 'no spill dog bowl': 0.361 (13/36)
      2. 'water bowl no spill': 0.333 (12/36)
      3. 'python no spill': 0.306 (11/36)
      4. 'dog water bowl no spill': 0.278 (10/36)
      5. 'no spill water bowl': 0.278 (10/36)

  --- FAT ---
    Violation Rate: 0.236, Compliant Rate: 0.306, UNCLEAR Rate: 0.458
    (2 search terms)
    Top search terms:
      1. 'fat free dog treats': 0.389 (14/36)
      2. 'no fat dog treats': 0.083 (3/36)

  --- FISH ---
    Violation Rate: 0.861, Compliant Rate: 0.056, UNCLEAR Rate: 0.083
    (1 search terms)
    Top search terms:
      1. 'fish free cat food': 0.861 (31/36)

  --- EARS ---
    Violation Rate: 0.708, Compliant Rate: 0.194, UNCLEAR Rate: 0.097
    (2 search terms)
    Top search terms:
      1. 'fly mask without ears': 0.750 (27/36)
      2. 'horse fly mask without ears': 0.667 (24/36)

  --- NON CLUMPING ---
    Violation Rate: 0.623, Compliant Rate: 0.353, UNCLEAR Rate: 0.024
    (7 search terms)
    Top search terms:
      1. 'non clumping cat litter': 0.833 (30/36)
      2. 'non clumping kitty litter': 0.833 (30/36)
      3. 'litter non clumping': 0.722 (26/36)
      4. 'unscented non clumping cat litter': 0.611 (22/36)
      5. 'fresh step cat litter non clumping': 0.472 (17/36)

  --- GAIN ---
    Violation Rate: 0.083, Compliant Rate: 0.917, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'gain free dog food': 0.083 (3/36)

  --- GLUTEN ---
    Violation Rate: 0.142, Compliant Rate: 0.647, UNCLEAR Rate: 0.211
    (10 search terms)
    Top search terms:
      1. 'victor hi-pro plus 30/20 active sporting high protein gluten-free dry dog food': 0.417 (15/36)
      2. 'gluten free puppy food': 0.306 (11/36)
      3. 'gluten free dry dog food': 0.250 (9/36)
      4. 'gluten free dog food': 0.167 (6/36)
      5. 'gluten free wet dog food': 0.139 (5/36)

  --- GMO ---
    Violation Rate: 0.012, Compliant Rate: 0.841, UNCLEAR Rate: 0.147
    (7 search terms)
    Top search terms:
      1. 'non gmo wet dog food': 0.083 (3/36)
      2. 'gmo free dog food': 0.000 (0/36)
      3. 'non gmo': 0.000 (0/36)
      4. 'non gmo cat food': 0.000 (0/36)
      5. 'non gmo chicken feed': 0.000 (0/36)

  --- GRAIN, CHICKEN ---
    Violation Rate: 0.549, Compliant Rate: 0.444, UNCLEAR Rate: 0.007
    (4 search terms)
    Top search terms:
      1. 'grain free chicken free dog food': 0.750 (27/36)
      2. 'grain free chicken free dog treats': 0.750 (27/36)
      3. 'grain and chicken free dog food': 0.694 (25/36)
      4. 'merrick real texas beef + sweet potato recipe grain-free chicken-free adult dry dog food': 0.000 (0/2)

  --- PROBIOTIC ---
    Violation Rate: 0.000, Compliant Rate: 0.000, UNCLEAR Rate: 1.000
    (1 search terms)
    Top search terms:
      1. 'grain free dogfood no probiotic': 0.000 (0/36)

  --- IODINE ---
    Violation Rate: 0.000, Compliant Rate: 0.028, UNCLEAR Rate: 0.972
    (1 search terms)
    Top search terms:
      1. 'iodine free cat food': 0.000 (0/36)

  --- CLUMPING ---
    Violation Rate: 0.097, Compliant Rate: 0.903, UNCLEAR Rate: 0.000
    (2 search terms)
    Top search terms:
      1. 'non clumping': 0.111 (4/36)
      2. 'kitty litter non clumping': 0.083 (3/36)

  --- LEGUME ---
    Violation Rate: 0.472, Compliant Rate: 0.028, UNCLEAR Rate: 0.500
    (1 search terms)
    Top search terms:
      1. 'legume free dog food': 0.472 (17/36)

  --- PILL ---
    Violation Rate: 1.000, Compliant Rate: 0.000, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'licks pill free': 1.000 (36/36)

  --- GRAIN, FAT ---
    Violation Rate: 1.000, Compliant Rate: 0.000, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'low fat grain free dog food': 1.000 (36/36)

  --- BARK ---
    Violation Rate: 0.889, Compliant Rate: 0.111, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'no bark': 0.889 (32/36)

  --- NO BARK ---
    Violation Rate: 1.000, Compliant Rate: 0.000, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'no bark collars': 1.000 (36/36)

  --- CAT PEE ---
    Violation Rate: 0.333, Compliant Rate: 0.667, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'no cat pee': 0.333 (12/36)

  --- CHEW ---
    Violation Rate: 0.300, Compliant Rate: 0.678, UNCLEAR Rate: 0.022
    (5 search terms)
    Top search terms:
      1. 'no chew': 0.861 (31/36)
      2. 'no chew spray for cats': 0.278 (10/36)
      3. 'no chew dog bed': 0.139 (5/36)
      4. 'no chew spray for dogs': 0.139 (5/36)
      5. 'non chew dog bed': 0.083 (3/36)

  --- CLUMP ---
    Violation Rate: 0.778, Compliant Rate: 0.222, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'no clump litter': 0.778 (28/36)

  --- GROW ---
    Violation Rate: 0.028, Compliant Rate: 0.306, UNCLEAR Rate: 0.667
    (1 search terms)
    Top search terms:
      1. 'no grow bird seed': 0.028 (1/36)

  --- HIDES ---
    Violation Rate: 0.111, Compliant Rate: 0.861, UNCLEAR Rate: 0.028
    (1 search terms)
    Top search terms:
      1. 'no hides': 0.111 (4/36)

  --- HOLES ---
    Violation Rate: 0.188, Compliant Rate: 0.781, UNCLEAR Rate: 0.031
    (1 search terms)
    Top search terms:
      1. 'no holes': 0.188 (6/32)

  --- LICK ---
    Violation Rate: 0.944, Compliant Rate: 0.056, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'no lick': 0.944 (34/36)

  --- NO MELT ---
    Violation Rate: 0.500, Compliant Rate: 0.222, UNCLEAR Rate: 0.278
    (1 search terms)
    Top search terms:
      1. 'no melt suet': 0.500 (18/36)

  --- MILLET ---
    Violation Rate: 0.389, Compliant Rate: 0.028, UNCLEAR Rate: 0.583
    (1 search terms)
    Top search terms:
      1. 'no millet bird seed': 0.389 (14/36)

  --- POOP EATING ---
    Violation Rate: 0.361, Compliant Rate: 0.583, UNCLEAR Rate: 0.056
    (1 search terms)
    Top search terms:
      1. 'no poop eating': 0.361 (13/36)

  --- SCOOT ---
    Violation Rate: 0.556, Compliant Rate: 0.417, UNCLEAR Rate: 0.028
    (1 search terms)
    Top search terms:
      1. 'no scoot for dogs': 0.556 (20/36)

  --- SPRAY ---
    Violation Rate: 1.000, Compliant Rate: 0.000, UNCLEAR Rate: 0.000
    (1 search terms)
    Top search terms:
      1. 'no spray cat': 1.000 (36/36)

  --- SQUIRREL ---
    Violation Rate: 0.333, Compliant Rate: 0.583, UNCLEAR Rate: 0.083
    (1 search terms)
    Top search terms:
      1. 'no squirrel bird seed': 0.333 (12/36)

  --- SUGAR ---
    Violation Rate: 0.211, Compliant Rate: 0.133, UNCLEAR Rate: 0.656
    (5 search terms)
    Top search terms:
      1. 'sugar free': 0.417 (15/36)
      2. 'sugar free horse treats': 0.306 (11/36)
      3. 'no sugar horse treats': 0.222 (8/36)
      4. 'sugar free dog treats': 0.083 (3/36)
      5. 'no sugar dog treats': 0.028 (1/36)

  --- TIP ---
    Violation Rate: 0.000, Compliant Rate: 0.875, UNCLEAR Rate: 0.125
    (2 search terms)
    Top search terms:
      1. 'no tip water bowl': 0.000 (0/36)
      2. 'non tip water bowl': 0.000 (0/36)

  --- TOOT ---
    Violation Rate: 0.258, Compliant Rate: 0.677, UNCLEAR Rate: 0.065
    (1 search terms)
    Top search terms:
      1. 'no toot': 0.258 (8/31)

  --- TRACK ---
    Violation Rate: 0.306, Compliant Rate: 0.194, UNCLEAR Rate: 0.500
    (1 search terms)
    Top search terms:
      1. 'no track cat litter': 0.306 (11/36)

  --- NON ABSORBENT ---
    Violation Rate: 0.500, Compliant Rate: 0.444, UNCLEAR Rate: 0.056
    (1 search terms)
    Top search terms:
      1. 'non absorbent cat litter': 0.500 (18/36)


## Export Metrics to CSV

In [15]:
# Export metrics: 2 simple CSVs covering all endpoints (lexical, knn, l1_hybrid, l2)

if not l1_metrics:
    print("No metrics available to export")
else:
    print(f"\n=== EXPORTING METRICS ===")
    
    # 1. AGGREGATED METRICS (averaged across all search terms)
    aggregated_data = []
    for endpoint, endpoint_metrics in l1_metrics.items():
        for k_level, k_metrics in endpoint_metrics.items():
            k_val = k_level.replace('K', '')
            aggregated_data.append({
                'variant': VARIANT,
                'endpoint': endpoint,
                'k': k_val,
                'violation_rate': k_metrics[f'violation_rate@{k_val}'],
                'compliant_rate': k_metrics[f'compliant_rate@{k_val}'],
                'unclear_rate': k_metrics[f'unclear_rate@{k_val}'],
                'total_search_terms': k_metrics['total_search_terms']
            })
    
    aggregated_df = pd.DataFrame(aggregated_data)
    aggregated_file = os.path.join(METRICS_OUTPUT_DIR, f'{VARIANT}_aggregated_metrics.csv')
    aggregated_df.to_csv(aggregated_file, index=False)
    print(f"✓ Aggregated metrics saved: {aggregated_file}")
    print(f"  Shape: {aggregated_df.shape} (rows × columns)")
    
    # 2. SEARCH TERM LEVEL METRICS (detailed per search term, per endpoint)
    search_term_data = []
    for endpoint, endpoint_metrics in l1_metrics.items():
        for k_level, k_metrics in endpoint_metrics.items():
            if 'search_term_details' in k_metrics:
                k_val = k_level.replace('K', '')
                for search_term, details in k_metrics['search_term_details'].items():
                    search_term_data.append({
                        'variant': VARIANT,
                        'endpoint': endpoint,
                        'k': k_val,
                        'search_term': search_term,
                        'violation_rate': details[f'violation_rate@{k_val}'],
                        'compliant_rate': details[f'compliant_rate@{k_val}'],
                        'unclear_rate': details[f'unclear_rate@{k_val}'],
                        'total_results': details['total_results'],
                        'violation_count': details['violation_count'],
                        'compliant_count': details['compliant_count'],
                        'unclear_count': details['unclear_count']
                    })
    
    search_term_df = pd.DataFrame(search_term_data)

    # Add negative_intent column from df_final
    if len(df_final) > 0 and 'negative_intent' in df_final.columns:
        search_term_to_intent = df_final.drop_duplicates('search_term')[['search_term', 'negative_intent']].set_index('search_term')['negative_intent'].to_dict()
        search_term_df['negative_intent'] = search_term_df['search_term'].map(search_term_to_intent)
        intent_coverage = search_term_df['negative_intent'].notna().sum()
        print(f"Added negative_intent: {intent_coverage}/{len(search_term_df)} rows have intent")
    else:
        search_term_df['negative_intent'] = None
        print("negative_intent column added (all null)")

    # Attach search_volume from candidates file using strict mapping (Q -> search_term, CNT -> search_volume)
    candidates_file = "./negative_intent_candidates(raw_data).csv"
    if os.path.exists(candidates_file):
        try:
            df_cand_raw = pd.read_csv(candidates_file)
            df_cand = df_cand_raw[['Q', 'CNT']].rename(columns={'Q': 'search_term', 'CNT': 'search_volume'})
            df_cand['search_volume'] = pd.to_numeric(df_cand['search_volume'], errors='coerce').fillna(0)
            df_cand = df_cand.sort_values('search_volume', ascending=False).drop_duplicates('search_term')
            before = len(search_term_df)
            search_term_df = search_term_df.merge(df_cand, on='search_term', how='left')
            attached = search_term_df['search_volume'].notna().sum()
            print(f"Attached search_volume for {attached}/{before} search-term rows")
        except Exception as e:
            print(f"Error merging search_volume: {e}")
    else:
        print("Candidates file not found; exporting without search_volume")
    
    search_term_file = os.path.join(METRICS_OUTPUT_DIR, f'{VARIANT}_search_term_metrics.csv')
    search_term_df.to_csv(search_term_file, index=False)
    print(f"✓ Search term metrics saved: {search_term_file}")
    print(f"  Shape: {search_term_df.shape} (rows × columns)")
    
    print(f"\n=== EXPORT COMPLETE ===")
    print(f"All files saved to: {METRICS_OUTPUT_DIR}")

=== EXPORTING METRICS ===
✓ Aggregated metrics saved: ./metrics_output/control/control_aggregated_metrics.csv
  Shape: (12, 7) (rows × columns)
Added negative_intent: 9534/9534 rows have intent
Attached search_volume for 9534/9534 search-term rows
✓ Search term metrics saved: ./metrics_output/control/control_search_term_metrics.csv
  Shape: (9534, 13) (rows × columns)

=== EXPORT COMPLETE ===
All files saved to: ./metrics_output/control

In [16]:
search_term_df.negative_intent.unique()

array(['pull', 'grain', 'aller', 'allergy', 'waste free', 'shock', 'odor',
       'mess', 'waste', 'melt', 'chicken', 'bpa', 'd3', 'hide', 'bell',
       'prescription', 'additives', 'dust', 'fragrance', 'scent',
       'tracking', 'pee', 'scratch', 'catnip', 'carpet', 'rawhide', 'poo',
       'poop', 'medicated', 'non gmo', 'soy', 'choke', 'sunflower seeds',
       'corn and soy', 'corn', 'free', 'seafood', 'poultry', 'escape',
       'zip', 'squeak', 'squeaker', 'stuffing', 'teeth', 'spill', 'fat',
       'fish', 'ears', 'non clumping', 'gain', 'gluten', 'gmo',
       'grain, chicken', 'probiotic', 'iodine', 'clumping', 'legume',
       'pill', 'grain, fat', 'bark', 'no bark', 'cat pee', 'chew',
       'clump', 'grow', 'hides', 'holes', 'lick', 'no melt', 'millet',
       'poop eating', 'scoot', 'spray', 'squirrel', 'sugar', 'tip',
       'toot', 'track', 'non absorbent', 'clay',
       'non clumping unscented cat litter\n\nthe user is actually looking for cat litter',
       'kibble', 'non prescription', 'scented', 'squeaky', 'stuffed',
       'toxic', 'pea', 'protein', 'rice', 'salt', 'shell', 'soy and corn',
       'stink', 'tear', 'unscented', 'stuff', 'dust, scent',
       'unscented\ndust', 'dehp', 'wheat', 'yeast'], dtype=object)

In [17]:
len(search_term_df.negative_intent.unique())

102